<a href="https://colab.research.google.com/github/Esheshwari/python-programming/blob/main/Esheshwari_Kumari_numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [ ]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [ ]:
# Create a 1-dimensional NumPy array using np.array()
import numpy as np

# Creating a 1D NumPy array
arr = np.array([1, 2, 3, 4, 5])
# Displaying the array
print(arr)

# Create a 2-dimensional NumPy array using np.array()
import numpy as np

# Creating a 2D NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Displaying the array
print(arr)

# Create a 3-dimensional Numpy array using np.array()
import numpy as np

# Creating a 3D NumPy array
arr = np.array([[[1, 2, 3], [4, 5, 6]],
                [[7, 8, 9], [10, 11, 12]]])
# Displaying the array
print(arr)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [ ]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
import numpy as np

# Creating a 1D NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Displaying attributes
print("Array:", arr)
print("Shape:", arr.shape)
print("Number of Dimensions:", arr.ndim)
print("Data Type:", arr.dtype)
print("Size:", arr.size)
print("Type:", type(arr))

Array: [10 20 30 40 50]
Shape: (5,)
Number of Dimensions: 1
Data Type: int64
Size: 5
Type: <class 'numpy.ndarray'>


In [ ]:
# Attributes of 2-dimensional array
import numpy as np

# Creating a 2D NumPy array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Displaying attributes
print("Array:\n", arr)
print("Shape:", arr.shape)
print("Number of Dimensions:", arr.ndim)
print("Data Type:", arr.dtype)
print("Size:", arr.size)
print("Type:", type(arr))


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of Dimensions: 2
Data Type: int64
Size: 6
Type: <class 'numpy.ndarray'>


In [ ]:
# Attributes of 3-dimensional array
import numpy as np

# Creating a 3D NumPy array
arr = np.array([[[1, 2, 3], [4, 5, 6]],
                [[7, 8, 9], [10, 11, 12]]])

# Displaying attributes
print("Array:\n", arr)
print("Shape:", arr.shape)
print("Number of Dimensions:", arr.ndim)
print("Data Type:", arr.dtype)
print("Size:", arr.size)
print("Type:", type(arr))


Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
Number of Dimensions: 3
Data Type: int64
Size: 12
Type: <class 'numpy.ndarray'>


In [ ]:
# Create an array of shape (10, 2) with only ones
import numpy as np

# Creating an array of ones with shape (10, 2)
arr = np.ones((10, 2))
# Displaying the array
print(arr)
# Verifying the shape
print("Shape of array:", arr.shape)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Shape of array: (10, 2)


In [ ]:
# Create an array of shape (7, 2, 3) of only zeros
import numpy as np

# Creating an array of zeros with shape (7, 2, 3)
arr = np.zeros((7, 2, 3))
# Displaying the array
print(arr)
# Verifying the shape
print("Shape of array:", arr.shape)



In [ ]:
# Create an array within a range of 0 and 100 with step 3
import numpy as np
# Creating an array with values from 0 to 100 (exclusive) with a step of 3
arr = np.arange(0, 100, 3)
# Displaying the array
print(arr)


[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [ ]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
import numpy as np
# Creating a random array with values between 0 and 10 of shape (7,2)
arr = np.random.randint(0, 10, size=(7, 2))
# Displaying the array
print(arr)

In [ ]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
import numpy as np
# Creating a random array of floats between 0 and 1 with shape (3, 5)
arr = np.random.rand(3, 5)
# Displaying the array
print(arr)

[[0.62336069 0.46064151 0.82661863 0.54528936 0.87943643]
 [0.01356616 0.81922147 0.04421051 0.78952805 0.22623172]
 [0.55578789 0.63940635 0.88084019 0.93007397 0.29788351]]


In [ ]:
# Set the random seed to 42

import numpy as np

# Set the random seed
np.random.seed(42)

# Creating a random array of integers between 0 and 10 with shape (4, 6)
arr = np.random.randint(0, 10, size=(4, 6))

# Displaying the array
print(arr)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [ ]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
import numpy as np

# Creating a random array of integers between 1 and 10 with shape (3, 7)
arr = np.random.randint(1, 11, size=(3, 7))

# Displaying the array
print("Array:\n", arr)

# Finding unique numbers in the array
unique_numbers = np.unique(arr)

# Displaying unique numbers
print("Unique Numbers:", unique_numbers)

Array:
 [[ 9  1 10  3  7  4  9]
 [ 3  5  3  7  5  9  7]
 [ 2  4  9  2 10  9 10]]
Unique Numbers: [ 1  2  3  4  5  7  9 10]


In [ ]:
# Find the 0'th index of the latest array you created
import numpy as np

# Creating a random array of integers between 1 and 10 with shape (3, 7)
arr = np.random.randint(1, 11, size=(3, 7))

# Displaying the array
print("Array:\n", arr)

# Accessing the 0th index (first row)
first_row = arr[0]

# Displaying the first row
print("0th Index (First Row):", first_row)

Array:
 [[ 5  2  4  7  8  3  1]
 [ 4  2  8  4  2  6  6]
 [10  4  6  2 10  2 10]]
0th Index (First Row): [5 2 4 7 8 3 1]


In [ ]:
# Get the first 2 rows of latest array you created
import numpy as np

# Creating a random array of integers between 1 and 10 with shape (3, 7)
arr = np.random.randint(1, 11, size=(3, 7))

# Displaying the array
print("Array:\n", arr)

# Getting the first 2 rows
first_two_rows = arr[:2]

# Displaying the first 2 rows
print("First 2 Rows:\n", first_two_rows)

Array:
 [[ 4  8  7  9  8  5  2]
 [ 5  8 10  9  9  1  9]
 [ 7  9  8  1  8  8  3]]
First 2 Rows:
 [[ 4  8  7  9  8  5  2]
 [ 5  8 10  9  9  1  9]]


In [ ]:
# Get the first 2 values of the first 2 rows of the latest array
import numpy as np

# Creating a random array of integers between 1 and 10 with shape (3, 7)
arr = np.random.randint(1, 11, size=(3, 7))

# Displaying the array
print("Array:\n", arr)

# Getting the first 2 values of the first 2 rows
subset = arr[:2, :2]

# Displaying the subset
print("First 2 values of the first 2 rows:\n", subset)

Array:
 [[ 1  8  3  3  1  5 10]
 [ 7 10  9  7  9  8  2]
 [ 1  7  7  8  5  3  8]]
First 2 values of the first 2 rows:
 [[ 1  8]
 [ 7 10]]


In [ ]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
import numpy as np

# Creating a random array of integers between 0 and 10 with shape (3, 5)
random_array = np.random.randint(0, 10, size=(3, 5))

# Creating an array of ones with shape (3, 5)
ones_array = np.ones((3, 5))

# Displaying the arrays
print("Random Array:\n", random_array)
print("\nArray of Ones:\n", ones_array)


Random Array:
 [[5 2 0 2 4]
 [2 0 4 9 6]
 [6 8 9 9 2]]

Array of Ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Add the two arrays together
import numpy as np

# Creating two arrays
array1 = np.random.randint(0, 10, size=(3, 5))
array2 = np.ones((3, 5), dtype=int)

# Adding the arrays
result = array1 + array2

# Printing the result
print(result)

[[ 7  1  4  4  5]
 [ 7  7  4  7  3]
 [ 6  2 10  9  5]]


In [ ]:
# Create another array of ones of shape (5, 3)
import numpy as np

# Creating an array of ones with shape (5, 3)
ones_array = np.ones((5, 3))

# Printing the array
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Try add the array of ones and the other most recent array together
import numpy as np

# Creating a (3, 5) random array
array1 = np.random.randint(0, 10, size=(3, 5))

# Creating a (5, 3) ones array and then transpose to (3, 5)
array2 = np.ones((5, 3), dtype=int).T

# Adding the arrays together
result = array1 + array2

print(result)


[[ 3  1  4  9  3]
 [ 9  7  4  3 10]
 [ 5  5  3  9  4]]


When you try the last cell, it produces an error. Why do think this is?
=> Its a ValueError as operands could not be broadcast together with shapes
 (3,5) (5,3)

How would you fix it?
Transpose one of the arrays (array2.T) to match dimensions:
result = array1 + array2.T
print(result)
Or reshape them into compatible shapes for broadcasting.

In [ ]:
# Create another array of ones of shape (3, 5)
import numpy as np

# Creating an array of ones with shape (3, 5)
ones_array = np.ones((3, 5), dtype=int)  # Using dtype=int to keep values as integers

# Printing the array
print(ones_array)


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
# Subtract the new array of ones from the other most recent array
import numpy as np

# Creating a (3,5) random array
array1 = np.random.randint(0, 10, size=(3, 5))

# Creating another (3,5) ones array
ones_array = np.ones((3, 5), dtype=int)

# Subtracting the ones array from the random array
result = array1 - ones_array

# Printing the arrays and result
print("Random Array:\n", array1)
print("\nArray of Ones:\n", ones_array)
print("\nResult after Subtraction:\n", result)


Random Array:
 [[7 8 4 0 2]
 [9 7 5 7 8]
 [3 0 0 9 3]]

Array of Ones:
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

Result after Subtraction:
 [[ 6  7  3 -1  1]
 [ 8  6  4  6  7]
 [ 2 -1 -1  8  2]]


In [ ]:
# Multiply the ones array with the latest array
import numpy as np

# Creating a (3,5) random array
array1 = np.random.randint(0, 10, size=(3, 5))

# Creating another (3,5) ones array
ones_array = np.ones((3, 5), dtype=int)

# Multiplying the ones array with the random array
result = array1 * ones_array

# Printing the arrays and result
print("Random Array:\n", array1)
print("\nArray of Ones:\n", ones_array)
print("\nResult after Multiplication:\n", result)

Random Array:
 [[6 1 2 0 4]
 [0 7 0 0 1]
 [1 5 6 4 0]]

Array of Ones:
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

Result after Multiplication:
 [[6 1 2 0 4]
 [0 7 0 0 1]
 [1 5 6 4 0]]


In [ ]:
# Take the latest array to the power of 2 using '**'
import numpy as np

# Creating a (3,5) random array
array1 = np.random.randint(0, 10, size=(3, 5))

# Squaring each element using '**'
result = array1 ** 2

# Printing the original array and result
print("Random Array:\n", array1)
print("\nArray Squared:\n", result)

Random Array:
 [[0 2 1 4 9]
 [5 6 3 6 7]
 [0 5 7 4 3]]

Array Squared:
 [[ 0  4  1 16 81]
 [25 36  9 36 49]
 [ 0 25 49 16  9]]


In [ ]:
# Do the same thing with np.square()
import numpy as np

# Creating a (3,5) random array
array1 = np.random.randint(0, 10, size=(3, 5))

# Squaring each element using np.square()
result = np.square(array1)

# Printing the original array and result
print("Random Array:\n", array1)
print("\nArray Squared:\n", result)

Random Array:
 [[1 5 5 0 8]
 [5 2 3 3 2]
 [9 2 2 3 6]]

Array Squared:
 [[ 1 25 25  0 64]
 [25  4  9  9  4]
 [81  4  4  9 36]]


In [ ]:
# Find the mean of the latest array using np.mean()
import numpy as np

# Creating a (3,5) random array
array1 = np.random.randint(0, 10, size=(3, 5))

# Finding the mean using np.mean()
mean_value = np.mean(array1)

# Printing the original array and mean
print("Random Array:\n", array1)
print("\nMean of the Array:", mean_value)

Random Array:
 [[3 8 0 7 6]
 [1 7 0 8 8]
 [1 6 9 2 6]]

Mean of the Array: 4.8


In [ ]:
# Find the maximum of the latest array using np.max()
import numpy as np

# Creating a (3,5) random array
array1 = np.random.randint(0, 10, size=(3, 5))

# Finding the maximum value using np.max()
max_value = np.max(array1)

# Printing the original array and maximum value
print("Random Array:\n", array1)
print("\nMaximum Value in the Array:", max_value)

Random Array:
 [[9 8 3 0 1]
 [0 4 4 6 8]
 [8 2 2 2 3]]

Maximum Value in the Array: 9


In [ ]:
# Find the minimum of the latest array using np.min()
import numpy as np

# Creating a (3,5) random array
array1 = np.random.randint(0, 10, size=(3, 5))

# Finding the minimum value using np.min()
min_value = np.min(array1)

# Printing the original array and minimum value
print("Random Array:\n", array1)
print("\nMinimum Value in the Array:", min_value)

Random Array:
 [[8 1 1 1 5]
 [2 8 3 0 3]
 [0 4 3 7 7]]

Minimum Value in the Array: 0


In [ ]:
# Find the standard deviation of the latest array
import numpy as np

# Creating a (3,5) random array
array1 = np.random.randint(0, 10, size=(3, 5))

# Finding the standard deviation using np.std()
std_dev = np.std(array1)

# Printing the original array and standard deviation
print("Random Array:\n", array1)
print("\nStandard Deviation of the Array:", std_dev)

Random Array:
 [[7 5 7 0 7]
 [3 0 7 3 5]
 [7 3 2 8 2]]

Standard Deviation of the Array: 2.6280537792569367


In [ ]:
# Find the variance of the latest array
import numpy as np

# Creating a (3,5) random array
array1 = np.random.randint(0, 10, size=(3, 5))

# Finding the variance using np.var()
variance = np.var(array1)

# Printing the original array and variance
print("Random Array:\n", array1)
print("\nVariance of the Array:", variance)

Random Array:
 [[6 2 0 0 2]
 [5 6 5 5 5]
 [2 5 7 1 4]]

Variance of the Array: 4.888888888888889


In [ ]:
# Reshape the latest array to (3, 5, 1)
import numpy as np

# Creating a (3,5) random array
array1 = np.random.randint(0, 10, size=(3, 5))

# Reshaping the array to (3,5,1)
reshaped_array = array1.reshape(3, 5, 1)

# Printing the original and reshaped array
print("Original Array Shape:", array1.shape)
print("\nReshaped Array Shape:", reshaped_array.shape)
print("\nReshaped Array:\n", reshaped_array)

Original Array Shape: (3, 5)

Reshaped Array Shape: (3, 5, 1)

Reshaped Array:
 [[[0]
  [0]
  [4]
  [2]
  [3]]

 [[2]
  [0]
  [0]
  [4]
  [5]]

 [[2]
  [8]
  [4]
  [7]
  [0]]]


In [ ]:
# Transpose the latest array
import numpy as np

# Creating a (3,5) random array
array1 = np.random.randint(0, 10, size=(3, 5))

# Reshaping to (3,5,1)
reshaped_array = array1.reshape(3, 5, 1)

# Transposing the reshaped array
transposed_array = reshaped_array.transpose(1, 0, 2)  # Swaps axes

# Printing shapes and transposed array
print("Original Shape:", reshaped_array.shape)
print("Transposed Shape:", transposed_array.shape)
print("\nTransposed Array:\n", transposed_array)

Original Shape: (3, 5, 1)
Transposed Shape: (5, 3, 1)

Transposed Array:
 [[[4]
  [6]
  [9]]

 [[2]
  [0]
  [5]]

 [[0]
  [2]
  [9]]

 [[3]
  [1]
  [2]]

 [[4]
  [8]
  [7]]]


What does the transpose do? =>The transpose operation rearranges the axes of an array, effectively flipping rows and columns (or higher-dimensional equivalents).

In [ ]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
import numpy as np

# Creating a (3,3) random integer array
array1 = np.random.randint(0, 10, size=(3, 3))

# Creating a (3,2) random integer array
array2 = np.random.randint(0, 10, size=(3, 2))

# Printing the generated arrays
print("First Array (3x3):\n", array1)
print("\nSecond Array (3x2):\n", array2)


First Array (3x3):
 [[7 1 5]
 [6 1 9]
 [1 9 0]]

Second Array (3x2):
 [[7 0]
 [8 5]
 [6 9]]


In [ ]:
# Perform a dot product on the two newest arrays you created
import numpy as np

# Creating two random arrays
array1 = np.random.randint(0, 10, size=(3, 3))  # Shape (3,3)
array2 = np.random.randint(0, 10, size=(3, 2))  # Shape (3,2)

# Performing dot product
dot_product = np.dot(array1, array2)  # OR array1 @ array2

# Printing the arrays and result
print("First Array (3x3):\n", array1)
print("\nSecond Array (3x2):\n", array2)
print("\nDot Product Result (3x2):\n", dot_product)


First Array (3x3):
 [[6 9 2]
 [1 8 7]
 [9 6 8]]

Second Array (3x2):
 [[3 3]
 [0 7]
 [2 6]]

Dot Product Result (3x2):
 [[ 22  93]
 [ 17 101]
 [ 43 117]]


In [ ]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
import numpy as np

# Creating two (4,3) random integer arrays
array1 = np.random.randint(0, 10, size=(4, 3))
array2 = np.random.randint(0, 10, size=(4, 3))

# Printing the generated arrays
print("First Array (4x3):\n", array1)
print("\nSecond Array (4x3):\n", array2)

In [ ]:
# Perform a dot product on the two newest arrays you created
import numpy as np

# Creating two (4,3) random integer arrays
array1 = np.random.randint(0, 10, size=(4, 3))
array2 = np.random.randint(0, 10, size=(4, 3))

# Transposing the first array to (3,4) so we can perform dot product
array1_T = array1.T  # Transpose from (4,3) to (3,4)

# Performing dot product
dot_product = np.dot(array1_T, array2)  # OR array1_T @ array2

# Printing the arrays and result
print("First Array (4x3):\n", array1)
print("\nSecond Array (4x3):\n", array2)
print("\nTransposed First Array (3x4):\n", array1_T)
print("\nDot Product Result (3x3):\n", dot_product)



First Array (4x3):
 [[1 5 8]
 [7 4 0]
 [6 4 5]
 [6 2 9]]

Second Array (4x3):
 [[2 4 5]
 [8 4 0]
 [3 4 9]
 [9 4 6]]

Transposed First Array (3x4):
 [[1 7 6 6]
 [5 4 4 2]
 [8 0 5 9]]

Dot Product Result (3x3):
 [[130  80  95]
 [ 72  60  73]
 [112  88 139]]


It doesn't work. How would you fix it?=>By transposing array1 to (3,4), the operation becomes:
(3,4) × (4,3) = (3,3) Now it works!
The final output is a (3,3) matrix instead of an invalid shape

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
import numpy as np

# Creating two (4,3) random integer arrays
array1 = np.random.randint(0, 10, size=(4, 3))
array2 = np.random.randint(0, 10, size=(4, 3))

# Transposing the second array to (3,4) to align dimensions
array2_T = array2.T  # (4,3) → (3,4)

# Performing dot product
dot_product = np.dot(array1, array2_T)  # OR array1 @ array2_T

# Printing the arrays and result
print("First Array (4x3):\n", array1)
print("\nSecond Array (4x3):\n", array2)
print("\nTransposed Second Array (3x4):\n", array2_T)
print("\nDot Product Result (4x4):\n", dot_product)


First Array (4x3):
 [[3 0 4]
 [6 9 9]
 [5 4 3]
 [1 3 9]]

Second Array (4x3):
 [[9 2 9]
 [0 7 4]
 [3 7 6]
 [1 0 3]]

Transposed Second Array (3x4):
 [[9 0 3 1]
 [2 7 7 0]
 [9 4 6 3]]

Dot Product Result (4x4):
 [[ 63  16  33  15]
 [153  99 135  33]
 [ 80  40  61  14]
 [ 96  57  78  28]]


Notice how performing a transpose allows the dot product to happen.

Why is this?=>Dot product rule: (m, n) * (n, p) = (m, p).
Both arrays start as (4,3), so we transpose one to (3,4).
This allows the dot product to result in a (4,4) matrix.

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
import numpy as np

# Create two arrays of random integers between 0 & 10 with the same shape
array1 = np.random.randint(0, 11, size=(5, 5))
array2 = np.random.randint(0, 11, size=(5, 5))

print(array1)
print(array2)

[[ 7  1  2  0  0]
 [ 2 10  4  2  0]
 [ 0  7  9 10  1]
 [ 2  1  2  6  0]
 [ 9  7  9  9  9]]
[[ 1  2  8  6  3]
 [ 9  4  1 10  7]
 [ 3  8  4  8  3]
 [ 9  4  8  7  2]
 [ 0  2  3  1  0]]


In [ ]:
# Compare the two arrays with '>'
import numpy as np

# Creating two NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 2, 1, 5, 4])

# Comparing the arrays using '>'
result = array1 > array2

print(result)


[False False  True False  True]


What happens when you compare the arrays with `>`?=>using the > operator, we get a new array of the same shape with boolean values. Each boolean value indicates whether the comparison is true or false for the corresponding elements of the original arrays.

In [ ]:
# Compare the two arrays with '>='
import numpy as np

# Creating two NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 2, 1, 5, 4])

# Comparing the arrays using '>='
result = array1 >= array2

print(result)

[False  True  True False  True]


In [ ]:
# Find which elements of the first array are greater than 7
import numpy as np

# Creating a NumPy array
array = np.array([3, 8, 6, 10, 7, 12, 5])

# Finding elements greater than 7
result = array > 7

print(result)

[False  True False  True False  True False]


In [ ]:
# Which parts of each array are equal? (try using '==')
import numpy as np

# Creating two NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 2, 1, 5, 4])

# Comparing the arrays using '=='
result = array1 == array2

print(result)


[False  True False False False]


In [ ]:
# Sort one of the arrays you just created in ascending order
import numpy as np

# Creating the NumPy array
array1 = np.array([1, 2, 3, 4, 5])

# Sorting the array in ascending order
sorted_array1 = np.sort(array1)

print(sorted_array1)


[1 2 3 4 5]


In [ ]:
# Sort the indexes of one of the arrays you just created
import numpy as np

# Creating the NumPy array
array2 = np.array([3, 2, 1, 5, 4])

# Sorting the indexes of the array
sorted_indexes = np.argsort(array2)

print(sorted_indexes)

[2 1 0 4 3]


In [ ]:
# Find the index with the maximum value in one of the arrays you've created
import numpy as np

# Creating the NumPy array
array2 = np.array([3, 2, 1, 5, 4])

# Finding the index with the maximum value
max_index = np.argmax(array2)

print(max_index)

3


In [ ]:
# Find the index with the minimum value in one of the arrays you've created
import numpy as np

# Creating the NumPy array
array2 = np.array([3, 2, 1, 5, 4])

# Finding the index with the minimum value
min_index = np.argmin(array2)

print(min_index)

2


In [ ]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
import numpy as np

# Creating a 2D NumPy array
array = np.array([[3, 2, 1],
                  [5, 4, 6],
                  [7, 8, 9]])

# Finding the indexes with the maximum values down the 1st axis (rows)
max_indexes = np.argmax(array, axis=1)

print(max_indexes)


[0 2 2]


In [ ]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
import numpy as np

# Creating a 2D NumPy array
array = np.array([[3, 2, 1],
                  [5, 4, 6],
                  [7, 8, 9]])

# Finding the indexes with the minimum values across the 0th axis (columns)
min_indexes = np.argmin(array, axis=0)

print(min_indexes)

[0 0 0]


In [ ]:
# Create an array of normally distributed random numbers
import numpy as np

# Creating an array of normally distributed random numbers
mean = 0     # Mean of the distribution
std_dev = 1  # Standard deviation of the distribution
size = 10    # Number of random numbers

random_array = np.random.normal(mean, std_dev, size)

print(random_array)

[-0.66920273  1.16193732  1.55285978 -0.43951788 -0.40791535  0.26162306
  0.01214651  0.93093408 -0.52318809  0.94914299]


In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100
import numpy as np

# Creating an array with 10 evenly spaced numbers between 1 and 100
evenly_spaced_array = np.linspace(1, 100, 10)

print(evenly_spaced_array)


[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.

What happens when you try to broadcast a (3,) array with a (4,) array?
=>Broadcasting in NumPy allows you to perform element-wise operations on arrays of different shapes. However, for broadcasting to work, the shapes of the arrays must be compatible according to certain rules. If the shapes are not compatible, the operation will fail.

When you try to broadcast a (3,) array with a (4,) array, the operation will fail because their shapes are not compatible.
Explain why this operation might fail and how to fix it.
=>It fails because:
  1.If the arrays do not have the same number of dimensions, prepend ones to the shape of the smaller array.

  2.The size of each dimension must either be the same or one of them must be 1.
To fix this issue, you need to make the shapes of the arrays compatible. One way to do this is by reshaping one of the arrays to a shape that can be broadcast with the other array.

In [ ]:
# code here
import numpy as np

# Creating two NumPy arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6, 7])

# Reshaping the arrays to be compatible for broadcasting
array1 = array1.reshape(1, 3)
array2 = array2.reshape(4, 1)

# Performing the element-wise addition
result = array1 + array2

print(result)


[[ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]


Write a NumPy program to add a 1D array of shape (3,) to a 2D array of shape (2, 3).


In [ ]:
import numpy as np

# Creating a 1D NumPy array of shape (3,)
array1 = np.array([1, 2, 3])

# Creating a 2D NumPy array of shape (2, 3)
array2 = np.array([[4, 5, 6],
                   [7, 8, 9]])

# Adding the 1D array to the 2D array using broadcasting
result = array2 + array1

print(result)

[[ 5  7  9]
 [ 8 10 12]]


Add a 1D array [10, 20, 30] to each row of a 2D array [[1, 2, 3], [4, 5, 6], [7, 8, 9]].

In [ ]:
import numpy as np

# Creating the 1D array and the 2D array
array1 = np.array([10, 20, 30])
array2 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Adding the 1D array to each row of the 2D array using broadcasting
result = array2 + array1

print(result)


[[11 22 33]
 [14 25 36]
 [17 28 39]]


Attempt to add a 1D array [10, 20] to a 2D array [[1, 2, 3], [4, 5, 6]]. Explain the error.

In [ ]:
import numpy as np

# Creating the 1D array and the 2D array
array1 = np.array([10, 20])
array2 = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Attempting to add the 1D array to the 2D array
try:
    result = array2 + array1
except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (2,3) (2,) 


Explanation of the Error:
The 1D array [10, 20] has shape (2,).

The 2D array [[1, 2, 3], [4, 5, 6]] has shape (2, 3).

According to the broadcasting rules:

When the arrays are aligned for broadcasting, the shapes must be compatible. Specifically, the size of each dimension must either be the same or one of them must be 1.

In this case:

The 2D array has 3 columns, while the 1D array has only 2 elements. Since the shapes are not compatible, the operation fails.

Multiply a 2D array [[1, 2], [3, 4]] with a 1D array [10, 20] using broadcasting.

In [ ]:
import numpy as np

# Creating the 2D array and the 1D array
array2d = np.array([[1, 2],
                    [3, 4]])
array1d = np.array([10, 20])

# Multiplying the 2D array with the 1D array using broadcasting
result = array2d * array1d

print(result)


[[10 40]
 [30 80]]


In [ ]:
#Broadcasting a scalar value:
import numpy as np

a = np.array([1.0, 2.0, 3.0])
b = 2.0

# Broadcasting the scalar b
result = a * b

print(result)


[2. 4. 6.]


In [ ]:
#Adding a 1D array to a 2D array:
import numpy as np

a = np.array([[1.0, 2.0, 3.0],
              [4.0, 5.0, 6.0]])
b = np.array([10.0, 20.0, 30.0])

# Broadcasting the 1D array b
result = a + b

print(result)

[[11. 22. 33.]
 [14. 25. 36.]]


In [ ]:
#Broadcasting two arrays of different shapes:
import numpy as np

a = np.array([[0.0, 0.0, 0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])

# Broadcasting the arrays a and b
result = a + b

print(result)

[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [ ]:
#Broadcasting rules illustration:
import numpy as np

# Arrays of shapes (4,3) and (3,)
a = np.arange(12).reshape(4, 3)
b = np.arange(3)

# Broadcasting the arrays a and b
result = a + b

print(result)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [ ]:
#Using broadcasting to subtract mean from each column:
import numpy as np

# Creating a 2D array
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Calculating the mean of each column
col_mean = a.mean(axis=0)

# Subtracting the mean from each column using broadcasting
result = a - col_mean

print(result)

[[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]
