<a href="https://colab.research.google.com/github/Esheshwari/python-programming/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr1=np.array([1,2,3])
print(arr1)
arr2=np.array([4,5,6])
print(arr2)
print(arr1+arr2)
print(arr2+4)

[1 2 3]
[4 5 6]
[5 7 9]
[ 8  9 10]


In [ ]:
arr1=np.array([1,2,3])
print(arr1)
arr2=np.array([[4],[5],[6]])
print(arr2)
print(arr1+arr2)

[1 2 3]
[[4]
 [5]
 [6]]
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([1,2,3,4])
#print(arr1+arr2)will give error as array shape/size is not same so numpy will give error

In [ ]:
arr1=np.array([[1,2,3], [4,5,6]])
arr2=np.array([2,2,2])
print(arr1+arr2)#this won't give error as size is same colomns are same rows wont matter

[[3 4 5]
 [6 7 8]]


In [ ]:
arr1=np.array([[1,2,3], [4,5,6]])
arr2=np.array([2,8,4])#this won't give error as size is same colomns are same rows wont matter
print(arr1+arr2)

[[ 3 10  7]
 [ 6 13 10]]


In [ ]:
arr1=np.array([[1,2], [4,5]])
arr2=np.array([2,8,4])
#print(arr1+arr2)this will again give error as size isn't same

In [ ]:
import numpy as np
x=np.array([1,2,3,4,5])
print(x)#this won't be executed with ,
print(type(x))#class numpy.ndarray
y=[1,2,3,4,5]
print(y)#this will be executed with ,
print(type(y))#class list

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5]
<class 'list'>


In [ ]:
#to convert list into array
import numpy as np
x=[1,2,3,4,5]
y=np.array(x)
z=np.array([1,2,3,4,5])#this will also convert it in array
print(y)##this will give output without , so that shows its converted to array
print(z)##this will give output without , so that shows its converted to array

[1 2 3 4 5]
[1 2 3 4 5]


In [ ]:
#Taking list as input then converting it to array
l=[]
for i in range (1,5):
  int_1=input("Enter : ")
  l.append(int_1)
print(np.array(l))

Enter : 6
Enter : 7
Enter : 4
Enter : 3
['6' '7' '4' '3']


In [ ]:
#printing array dim shapes etc
import numpy as np
arr1=np.array([1, 2, 3, 4])
print(arr1)
print(arr1.ndim)
print(arr1.shape)
#2-D
arr2=np.array([[1, 2, 3, 4], [5,6,7,8]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)
#3-D
arr3=np.array([[[1, 2, 3, 4],[8,9,6,7], [5,6,7,8]]])
print(arr3)
print(arr3.ndim)
print(arr3.shape)
#n dim(nd)
arr4=np.array([1,2,3,4], ndmin=10)
print(arr4)
print(arr4.ndim)
print(arr4.shape)

[1 2 3 4]
1
(4,)
[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
[[[1 2 3 4]
  [8 9 6 7]
  [5 6 7 8]]]
3
(1, 3, 4)
[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
(1, 1, 1, 1, 1, 1, 1, 1, 1, 4)


In [ ]:
#all element as zero
#1-D
arr_zero=np.zeros(4)
print(arr_zero)
print(arr_zero.ndim)
print(arr_zero.shape)

#2-D
arr2_zero=np.zeros((4, 5))
print(arr2_zero)
print(arr2_zero.ndim)
print(arr2_zero.shape)

#3-D
arr3_zero=np.zeros(((2, 3, 4)))
print(arr3_zero)
print(arr3_zero.ndim)
print(arr3_zero.shape)

[0. 0. 0. 0.]
1
(4,)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
2
(4, 5)
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3
(2, 3, 4)


In [ ]:
#all element as zero
#1-D
arr_one=np.ones(4)
print(arr_one)
print(arr_one.ndim)
print(arr_one.shape)

#2-D
arr2_one=np.ones((4, 5))
print(arr2_one)
print(arr2_one.ndim)
print(arr2_one.shape)

#3-D
arr3_one=np.ones(((2, 3, 4)))
print(arr3_one)
print(arr3_one.ndim)
print(arr3_one.shape)

[1. 1. 1. 1.]
1
(4,)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2
(4, 5)
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3
(2, 3, 4)


In [ ]:
#Empty array
arr_empty=np.empty(4)#previous data will be printed in case of empty
print(arr_empty)

[0. 0. 0. 0.]


In [ ]:
#for printing range of array
import numpy as np
ar_rn=np.arange(1, 4)
ar1_rn=np.arange(4)
print(ar_rn)
print(ar1_rn)

[1 2 3]
[0 1 2 3]


In [ ]:
#for identity matrix
import numpy as np
ar_dia=np.eye(3)#eye for identity mat
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#for matrix
import numpy as np
ar1_dia=np.eye(3, 5)#5=cols
print(ar1_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [ ]:
#linspace=for gapp(rem spelling)
import numpy as np
arr_lin=np.linspace(0, 20, 5)#0=start val, 20=end val,
print(arr_lin)
arr1_lin=np.linspace(0, 20, 4)
print(arr1_lin)

[ 0.  5. 10. 15. 20.]
[ 0.          6.66666667 13.33333333 20.        ]


In [ ]:
#Random
#rand()
#1-D
import numpy as np
arr_rn=np.random.rand(4)#generates random value btw 0 & 1
print(arr_rn)
#2-D
import numpy as np
arr_rn1=np.random.rand(4, 5)#generates random value btw 0 & 1
print(arr_rn1)
#3-D
import numpy as np
arr_rn2=np.random.rand(2, 3, 4)#generates random value btw 0 & 1
print(arr_rn2)

[0.14899713 0.49722658 0.79806628 0.84700554]
[[0.43625599 0.16062201 0.14813546 0.34620337 0.36101928]
 [0.03869375 0.15167744 0.87079851 0.37139672 0.86928111]
 [0.08401859 0.12684304 0.79625122 0.64622858 0.11005058]
 [0.61692298 0.80854465 0.75581082 0.83179793 0.31021461]]
[[[0.34997772 0.73263801 0.12528068 0.05429456]
  [0.56010032 0.35982447 0.3879816  0.28033521]
  [0.62007928 0.13374162 0.01767383 0.8152618 ]]

 [[0.51701673 0.51447631 0.56745658 0.88996157]
  [0.29492627 0.78303536 0.52453534 0.86172736]
  [0.98200434 0.54104328 0.3515126  0.29704477]]]


In [ ]:
#randn()
#1-D
import numpy as np
arr_rnn=np.random.randn(4)#generates random value close to 0 (can be + or -)
print(arr_rn)
#2-D
import numpy as np
arr_rnn1=np.random.randn(4, 5)#generates random value close to 0 (can be + or -)
print(arr_rnn1)
#3-D
import numpy as np
arr_rnn2=np.random.randn(2, 3, 4)#generates random value close to 0 (can be + or -)
print(arr_rnn2)

[-0.61964299 -0.77879324  0.2426038  -2.20531268]
[[-0.4670259   1.56254631 -0.20845633  1.87709871  0.30963069]
 [ 0.98860404 -0.00260013  0.58087785  0.37446667 -0.69560984]
 [-0.40696655  0.23343939 -0.19939378 -0.15446848 -0.0494105 ]
 [ 0.89625474  0.1501557   0.47522742  2.07881317 -0.08214688]]
[[[ 0.81449357 -1.07006301  1.07458447 -0.57254407]
  [ 1.58991812 -0.33565463  0.84005917  0.59073074]
  [ 1.16217417  0.22817043  0.89151247 -1.04126486]]

 [[-0.58319048 -1.3663501  -1.25827639 -0.57894438]
  [-0.55366692  0.10804262 -0.1109761  -1.10268267]
  [-0.99863041  0.17657228 -0.38326817  0.10915882]]]


In [ ]:
#ranf():function in NumPy is used to generate random float values between 0 (inclusive) and 1 (exclusive) that means 1 wont be included
#1-D
import numpy as np
arr_rnf=np.random.ranf(4)#generates random float value
print(arr_rnf)
#2-D
import numpy as np
arr_rnf1=np.random.ranf((4, 5))#generates random float value
print(arr_rnf1)
#3-D
import numpy as np
arr_rnf2=np.random.ranf(((2, 3, 4)))#generates random float value
print(arr_rnf2)

[0.88653521 0.75616454 0.88713949 0.83051803]
[[0.67064224 0.47331672 0.43461782 0.25044799 0.89708658]
 [0.92746832 0.59992193 0.45712222 0.12034909 0.2040389 ]
 [0.88262243 0.98748379 0.55352712 0.93591054 0.82665106]
 [0.5959885  0.28676014 0.97976535 0.99202494 0.96020336]]
[[[0.72999462 0.66587454 0.77567661 0.62420649]
  [0.4851849  0.34637398 0.01896775 0.56693588]
  [0.95088601 0.37426652 0.70221487 0.97628826]]

 [[0.53355548 0.07055818 0.46267393 0.64942953]
  [0.55247722 0.12956032 0.92751621 0.43043796]
  [0.897729   0.94887851 0.84869423 0.65570524]]]


In [ ]:
#randint
import numpy as np
arr_raint=np.random.randint(4, 20, 5)
print(arr_raint)

[ 8  4 15 14 10]


In [ ]:
#to change datatype
import numpy as np
x3=np.array([1, 2, 3, 4])
new_1=x3.astype(float)#astype func changes any datatype
print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]


In [ ]:
#shaping
import numpy as np
var_1=np.array([[1,2,3,4],[5,6,7,8]], ndmin=5)
print(var_1.ndim)
print()#to change shape
print(var_1)

5

[[[[[1 2 3 4]
    [5 6 7 8]]]]]


In [ ]:
#shaping
var1=np.array([1,2,3,4], ndmin=4)
print(var1)
print()
print(var1.ndim)
print(var1.shape)

[[[[1 2 3 4]]]]

4
(1, 1, 1, 4)


In [ ]:
#reshaping
var2=np.array([1,2,3,4])
print(var2)
print(var2.ndim)
print(var2.shape)
print()
#x= var2.reshape(3, 2)this will give error as 3*2=6 elements are needed to reshape here
x=var2.reshape(2,2)#this is possible as 2*2=4
print(x)#2,2
#converting to 2D
var3=np.array([1,2,3,4,5,6])
print(var3)
print(var3.ndim)
print(var3.shape)
print()
x1=var3.reshape(3,2)
print(x1)

#converting to 3D
var4=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var4)
print(var4.ndim)
print(var4.shape)
print()
x2=var4.reshape(2,2,3)
print(x2)
#to convert it back to 1-D
one=x2.reshape(-1)
print(one)
print(one.ndim)

[1 2 3 4]
1
(4,)

[[1 2]
 [3 4]]
[1 2 3 4 5 6]
1
(6,)

[[1 2]
 [3 4]
 [5 6]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [ ]:
#Arithmetic operation
#for add
import numpy as np
print("for add")
var_A=np.array([1,2,3,4,5])
var_B=np.array([2,3,4,5,7])
var_add=var_A+3
var_add1=var_A+var_B
print(var_add)
print(var_add1)
#for subtract
import numpy as np
print("for subtract")
var_C=np.array([1,2,3,4,5])
var_D=np.array([2,3,4,5,7])
var_sub=var_A-3
var_sub1=var_A-var_B
print(var_sub)
print(var_sub1)
#for multiply
import numpy as np
print("for mul")
var_E=np.array([1,2,3,4,5])
var_F=np.array([2,3,4,5,7])
var_mul=var_A*3
var_mul1=var_A*var_B
print(var_mul)
print(var_mul1)
#for div
import numpy as np
print("for div")
var_G=np.array([1,2,3,4,5])
var_H=np.array([2,3,4,5,7])
var_div=var_A/3
var_div1=var_A/var_B
print(var_div)
print(var_div1)
#for modulus
import numpy as np
print("for mod")
var_I=np.array([1,2,3,4,5])
var_J=np.array([2,3,4,5,7])
var_mod=var_I%3
var_mod1=var_I%var_J
print(var_mod)
print(var_mod1)
#for reciprocal
import numpy as np
print("for reciprocal")
var_r=np.array([1,2,3,4,5])#rec of 1=1/1, rec of 2=1/2, rec of 3=1/3.....
var_rec=np.reciprocal(var_r)
print(var_rec)

for add
[4 5 6 7 8]
[ 3  5  7  9 12]
for subtract
[-2 -1  0  1  2]
[-1 -1 -1 -1 -2]
for mul
[ 3  6  9 12 15]
[ 2  6 12 20 35]
for div
[0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0.5        0.66666667 0.75       0.8        0.71428571]
for mod
[1 2 0 1 2]
[1 2 3 4 5]
for reciprocal
[1 0 0 0 0]


In [ ]:
#other arithmetic func
#min and max
import numpy as np
var_m=np.array([1,2,3,4,5])
print("min: ",np.min(var_m))
print("max: ",np.max(var_m))
#argmin & argmax=prints position
print("argmin: ",np.argmin(var_m))#prints index of min
print("argmax: ",np.argmax(var_m))#prints index of max
#specific row & col min and max using axis, axis0=col, axis1=row
var_b=np.array([[1,2,3], [4,5,6]])
print(np.min(var_b, axis=0))#this will check min in col, out of 1 and 4= 1 is min, 2&5=2 is min, 3&6=3 is min
print(np.min(var_b, axis=1))#this will check min in row, In the first row [1, 2, 3], the minimum value is 1. In the second row [4, 5, 6], the minimum value is 4.
print(np.max(var_b, axis=0))
print(np.max(var_b, axis=1))
#square root
var_sq=np.array([9, 16, 25, 36, 100])
print("square root: ", np.sqrt(var_sq))
var_cs=np.array([3,4,5])
print("cos: ",np.cos(var_cs))
print("sin: ",np.sin(var_cs))
print("tan: ",np.tan(var_cs))
print("cumsum: ", np.cumsum(var_cs))#3, (3+4)=7, (7+5)=12

min:  1
max:  5
argmin:  0
argmax:  4
[1 2 3]
[1 4]
[4 5 6]
[3 6]
square root:  [ 3.  4.  5.  6. 10.]
cos:  [-0.9899925  -0.65364362  0.28366219]
sin:  [ 0.14112001 -0.7568025  -0.95892427]
tan:  [-0.14254654  1.15782128 -3.38051501]
cumsum:  [ 3  7 12]


In [ ]:
#Broadcasting
import numpy as np
var_B1=np.array([1,2,3])
print(var_B1)
print(var_B1.shape)
var_B2=np.array([[4],[2],[3]])
print(var_B2)
print(var_B2.shape)
print(var_B1+ var_B2)

[1 2 3]
(3,)
[[4]
 [2]
 [3]]
(3, 1)
[[5 6 7]
 [3 4 5]
 [4 5 6]]


In [ ]:
#Broadcasting
import numpy as np
var_B3=np.array([[1],[2]])
print(var_B3)
print(var_B3.shape)
var_B4=np.array([[[1,2,3],[2,4,5]]])#no. of cols should be same to no. of rows
print(var_B4)
print(var_B4.shape)
print(var_B3+ var_B4)

[[1]
 [2]]
(2, 1)
[[[1 2 3]
  [2 4 5]]]
(1, 2, 3)
[[[2 3 4]
  [4 6 7]]]


In [ ]:
#Indexing
import numpy as np
var_idx=np.array([1,2,3,4])
print(var_idx[3])
print(var_idx[-1])

var_idx2=np.array([[2,3,4], [5,6,7]])
print()
print(var_idx2)
print(var_idx2.ndim)
print(var_idx2[0,2])#0th row 2nd element

var_idx3=np.array([[[2,3,4], [5,6,7]]])
print()
print(var_idx3)
print(var_idx3.ndim)
print(var_idx3[0,1,2])#oth axes 1st row 2nd element

4
4

[[2 3 4]
 [5 6 7]]
2
4

[[[2 3 4]
  [5 6 7]]]
3
7


In [ ]:
#slicing
#for 1-D
import numpy as np
var_sl=np.array([1,2,3,4,5,6,7])
print(var_sl[1:-3])#start, stop, step
print(var_sl[1:4])
print(var_sl[1:])
print(var_sl[:4])
print(var_sl[1:6:2])
print(var_sl[::1])
#for 2-D
var_s2=np.array([[1,2,3,4,5,6,7],[8,9,5,4,6,5,7]])
print(var_s2.ndim)
print(var_s2[1, 2:5])#row, start:stop:step

#for 3-D
var_s3=np.array([[[1,2,3,4,5,6,7],[8,9,5,4,6,5,7],[2,3,4,5,6,7,8]]])
print(var_s3.ndim)
print(var_s3[0, 2, 1:6:1])#axes, row, start:stop:step

[2 3 4]
[2 3 4]
[2 3 4 5 6 7]
[1 2 3 4]
[2 4 6]
[1 2 3 4 5 6 7]
2
[5 4 6]
3
[3 4 5 6 7]


In [ ]:
#iteration
#for 1-D
import numpy as np
var_it=([1,2,3,4,5,6,7,8,9])
for i in var_it:
  print(i)
#for 2-D
var_it1=([[1,2,3,4],[5,6,7,8,9]])
for i in var_it1:
  print(i)

for j in var_it1:#to print elements without row
  for k in j:
    print(k)

#for 3-D
var_it2=np.array([[1,2,3,4,5],[5,6,7,8,9], [4,5,6,7,8]])
for i in var_it2:
  print(i)

for i in var_it2:#to print elements without row
  for j in i:
      print(j)
#instead of above matter use nditer:
print("with nditer:")
for i in np.nditer(var_it2, flags=['buffered'], op_dtypes=["S"]):#S is capital, to change data type use these fun
  print(i)
# for seeing idx use ndnumerate:
print("For indexing")
var_it2=np.array([[1,2,3,4,5],[5,6,7,8,9], [4,5,6,7,8]])
for i,d in np.ndenumerate(var_it2):
  print(i,d)

1
2
3
4
5
6
7
8
9
[1, 2, 3, 4]
[5, 6, 7, 8, 9]
1
2
3
4
5
6
7
8
9
[1 2 3 4 5]
[5 6 7 8 9]
[4 5 6 7 8]
1
2
3
4
5
5
6
7
8
9
4
5
6
7
8
with nditer:
b'1'
b'2'
b'3'
b'4'
b'5'
b'5'
b'6'
b'7'
b'8'
b'9'
b'4'
b'5'
b'6'
b'7'
b'8'
For indexing
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(1, 4) 9
(2, 0) 4
(2, 1) 5
(2, 2) 6
(2, 3) 7
(2, 4) 8


In [7]:
#Copy VS View
import numpy as np
var_c=np.array([1,2,3,4,5])
var_cp=var_c.copy()
print("var_c=", var_c)
print("Copy: ", var_cp)

import numpy as np
var_v=np.array([7,6,8,9,5])
var_vi=var_v.view()
print("var_v= ", var_v)
print("view: ",var_vi)

#changes affect view but not copy
import numpy as np
var_c=np.array([1,2,3,4,5])
var_cp=var_c.copy()
var_c[1]=40
print("var_c=", var_c)
print("Copy: ", var_cp)#in this array there wont be any change or 40 wont be seen in this

import numpy as np
var_v=np.array([7,6,8,9,5])
var_vi=var_v.view()
var_v[1]=20
print("var_v= ", var_v)
print("view: ",var_vi)#20 will be seen in this

var_c= [1 2 3 4 5]
Copy:  [1 2 3 4 5]
var_v=  [7 6 8 9 5]
view:  [7 6 8 9 5]
var_c= [ 1 40  3  4  5]
Copy:  [1 2 3 4 5]
var_v=  [ 7 20  8  9  5]
view:  [ 7 20  8  9  5]



The Difference Between Copy and View :

The view does not own the data .
A view is the view of the original array.

any changes made to the view will
affect the original array, and any
changes made to the original
will affect the view.

The copy owns the data.

The copy of an array is a new
array.

The changes made in the copy
data does not reflect in the
original array.

copy stores array in new address whereas view doesn't
  






In [18]:
#join and split
import numpy as np
j=np.array([1,2,3,4,5])
i=np.array([6,7,8,9])
arr=np.concatenate((j,i))
print(arr)
import numpy as np
j_1=np.array([[1,2],[3,4]])
i1=np.array([[6,7],[8,9]])
arr1=np.concatenate((j_1,i1))
arr1=np.concatenate((j_1,i1), axis=1)
print(arr1)
import numpy as np
j_2=np.array([[1,2],[3,4]])
i2=np.array([[6,7],[8,9]])
arr2=np.stack((j_2,i2), axis=1)
print(arr2)
import numpy as np
j_3=np.array([[1,2],[3,4]])
i3=np.array([[6,7],[8,9]])
arr3=np.hstack((j_3,i3))#horizontal:works along row
arr4=np.vstack((j_3,i3))#works along coloumn
arr5=np.dstack((j_3,i3))#works along height
print(arr3)
print(arr4)
print(arr5)

[1 2 3 4 5 6 7 8 9]
[[1 2 6 7]
 [3 4 8 9]]
[[[1 2]
  [6 7]]

 [[3 4]
  [8 9]]]
[[1 2 6 7]
 [3 4 8 9]]
[[1 2]
 [3 4]
 [6 7]
 [8 9]]
[[[1 6]
  [2 7]]

 [[3 8]
  [4 9]]]


In [23]:
#split
import numpy as np
j_s=np.array([1, 2, 3,4])
i_s=np.array([6,7,8,9])
arr7=np.array_split(j_s, 4)
arr8=np.array_split(i_s, 4)
print(arr7)
print(arr8)

js_2=np.array([[1,2],[2,3],[4,5],[6,7]])
arr9=np.array_split(js_2, 4)
arr0=arr9=np.array_split(js_2, 4, axis=1)
print(arr9)
print(arr0)

[array([1]), array([2]), array([3]), array([4])]
[array([6]), array([7]), array([8]), array([9])]
[array([[1],
       [2],
       [4],
       [6]]), array([[2],
       [3],
       [5],
       [7]]), array([], shape=(4, 0), dtype=int64), array([], shape=(4, 0), dtype=int64)]
[array([[1],
       [2],
       [4],
       [6]]), array([[2],
       [3],
       [5],
       [7]]), array([], shape=(4, 0), dtype=int64), array([], shape=(4, 0), dtype=int64)]


In [26]:
#search
import numpy as np
wh=np.array([1,2,3,4,5,6])
x=np.where(wh== 2)
y=np.where(wh% 2==0)#for even
print(x)
print(y)

(array([1]),)
(array([1, 3, 5]),)


In [28]:
#search sort
import numpy as np
wh1=np.array([1,2,3,5,6])
x1=np.searchsorted(wh1, 4)#this  will print idx where 4 should be put
y1=np.searchsorted(wh1, [4,5,6], side="right")
print(x1)
print(y1)

3
[3 4 5]


In [30]:
#sort
import numpy as np
wh3=np.array([1,2,3,5,6,11,7,44,33,27,8,9,0,22])
print(np.sort(wh3))
wh4=np.array(["a", "b", "t", "r", "g"])
print(np.sort(wh4))
wh5=np.array([[[1,2,3],[5,6,11],[7,44,33],[27,8,9],[0,22, 89]]])
print(np.sort(wh5))

[ 0  1  2  3  5  6  7  8  9 11 22 27 33 44]
['a' 'b' 'g' 'r' 't']
[[[ 1  2  3]
  [ 5  6 11]
  [ 7 33 44]
  [ 8  9 27]
  [ 0 22 89]]]


In [31]:
#filter
import numpy as np
wh6=np.array(["a", "b", "t", "r", "g"])
f=[True, False, True, False, True]
new_wh6=wh6[f]
print(new_wh6)

['a' 't' 'g']


In [34]:
#shuffle
import numpy as np
wh7=np.array([1,2,3,4,5,6,7])
np.random.shuffle(wh7)#it will randomly shuffle the array
print(wh7)


[4 2 1 3 6 7 5]


In [37]:
#unique
import numpy as np
wh8=np.array([1,2,2,3,4,5,6,6,6,7,7,8,9,8,7,5,9,9,0])#it will not print elements more than once it will convert array to unique elements array
x8=np.unique(wh8)
x9=np.unique(wh8, return_index=True)#index of el
x10=np.unique(wh8, return_counts=True)#return count of el
print(x8)
print(x9)
print(x10)

[0 1 2 3 4 5 6 7 8 9]
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([18,  0,  1,  3,  4,  5,  6,  9, 11, 12]))
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 1, 2, 1, 1, 2, 3, 3, 2, 3]))


In [41]:
#resize
import numpy as np
w1=np.array([1,2,3,4,5,6,7,8])
z=np.resize(w1, (2,3))#2 row, 3 col
y=z.flatten()#again back to prev shape
u=z.flatten(order="C")
v=z.flatten(order="A")
s=z.flatten(order="K")
t=z.flatten(order="F")
print(z)
print(y)
print(u)
print(v)
print(s)
print(t)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 4 2 5 3 6]


Order : {'C', 'F', 'A', 'K'}, Optional
> 'C' means to flatten in row-major (C-style) order.
A
> 'F' means to flatten in column-major (Fortran-style) order.

> 'A' means to flatten in column-major order if `a' is Fortran *contiguous*
in memory, row-major order otherwise.

> 'K' means to flatten `a' in the order the elements occur in memory

> The default is 'C'.

In [48]:
#ravel
import numpy as np

n = np.array([1, 2, 3, 4, 5, 6])
z = np.resize(n, (3, 2))
print(np.ravel(n, order="F"))  # Flattened array in Fortran (column-major) order




[1 2 3 4 5 6]


In [67]:
#insert
m= np.array([1, 2, 3, 4, 5, 7])
o=np.insert(m, 2, 50)#var, index to insert, value to insert
p=np.insert(m, (2,4), 50)
print (o)
print (p)

l=np.array([[1, 2, 3], [4, 5, 7]])
li=np.insert(l, 2, 6, axis=1)#2 is index where 6 will will be inserted since axis=1 so in cols
pi=np.insert(l, 2, 6, axis=0)#2 is index where 6 will will be inserted since axis=0 so in rows
si=np.insert(l, 2, [22,23], axis=1)#axis cant be zero here This works because you're inserting
#an array [22, 23] at column index 2. Each value (22 and 23) corresponds to a row in the original array l. So it inserts 22 in the first row and 23 in the second row.'''
ki=np.insert(l, 2, [22,23,24], axis=0)#axis cant be one
print(li)
print(pi)
print(si)
print(ki)
#use delete same way

[ 1  2 50  3  4  5  7]
[ 1  2 50  3  4 50  5  7]
[[1 2 6 3]
 [4 5 6 7]]
[[1 2 3]
 [4 5 7]
 [6 6 6]]
[[ 1  2 22  3]
 [ 4  5 23  7]]
[[ 1  2  3]
 [ 4  5  7]
 [22 23 24]]


In [68]:
#matrix vs array
import numpy as np
m1=np.matrix([[1,2,3], [4,5,6]])
print(m1)
print(type(m1))#main diff
a1=np.array([[1,2,3], [4,5,6]])
print(a1)
print(type(a1))#main diff

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [82]:
#Arithmetic function in matrix
import numpy as np
m3=np.matrix([[1,2,3], [4,5,6]])
m4=np.matrix([[7,8,9], [6,5,4]])
print("Add: ", m3+m4)
print("Sub: ", m3-m4)
#print(m3*m4)this wont be executed bcz Here, m3 has 3 columns, and m4 has 2 rows. To perform matrix multiplication, the number of columns in m3 must match the number of rows in m4.
#but we can use dot
#for the cond when row col is not eq
m32=np.matrix([[1,2], [1,2]])
m42=np.matrix([[1,2], [1,2]])
print(m32)
print(type(m32))
print()
print(m32*m42)
print()
print("dot: ", m32.dot(m42))

print("division: ", m3/m4)
print("Mod: ", m3%m4)
#for mul
import numpy as np

m31 = np.matrix([[1, 2, 3], [4, 5, 6]])
m41 = np.matrix([[7, 8], [9, 6], [5, 4]])  # Adjusted to a 3x2 matrix

result = m31 * m41

print("Mul: ",  result)







Add:  [[ 8 10 12]
 [10 10 10]]
Sub:  [[-6 -6 -6]
 [-2  0  2]]
[[1 2]
 [1 2]]
<class 'numpy.matrix'>

[[3 6]
 [3 6]]

dot:  [[3 6]
 [3 6]]
division:  [[0.14285714 0.25       0.33333333]
 [0.66666667 1.         1.5       ]]
Mod:  [[1 2 3]
 [4 0 2]]
Mul:  [[ 40  32]
 [103  86]]


In [83]:
#matrix Function:
#Transpose
import numpy as np
t2=np.matrix([[1,2,3], [4,5,6]])
print(t2)
print(np.transpose(t2))#prints transpose
print(t2.T)#prints transpose


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [89]:
#swapaxes
import numpy as np
t3=np.matrix([[1,2,3], [4,5,6]])
print(t3)
print(np.swapaxes(t3,0,1))#swap axes 0 to 1

import numpy as np
t31=np.matrix([[1,2], [3,4]])
print("t31: ", t31)
print("square swapping: ", np.swapaxes(t31,0,1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
t31:  [[1 2]
 [3 4]]
square swapping:  [[1 3]
 [2 4]]


The transpose method swaps the array's axes, effectively reversing the shape of the array. For a 2D array, it converts rows to columns and columns to rows.

The swapaxes method allows you to swap two specified axes of an array. This is particularly useful for higher-dimensional arrays where you need more control over the axis swapping.

In [90]:
#inverse
import numpy as np
t33=np.matrix([[1,2], [3,4]])
print("t33: ", t33)
print(np.linalg.inv(t33))

t33:  [[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [96]:
#power of matrix
import numpy as np
t36=np.matrix([[1,2], [3,4]])
print("t36: ", t36)
print("power 2: ", np.linalg.matrix_power(t33, 2))#power=2
print("power 3: ", np.linalg.matrix_power(t33, 3))#power=3
print("power 0: ", np.linalg.matrix_power(t33, 0))#power=0
print("power -2: ", np.linalg.matrix_power(t33, -2))#power=-2

t36:  [[1 2]
 [3 4]]
power 2:  [[ 7 10]
 [15 22]]
power 3:  [[ 37  54]
 [ 81 118]]
power 0:  [[1 0]
 [0 1]]
power -2:  [[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [98]:
#Determinant
import numpy as np
t38=np.matrix([[1,2,3], [3,4,3], [1,2,3]])
print(t38)
print(np.linalg.det(t38))


[[1 2 3]
 [3 4 3]
 [1 2 3]]
0.0
