<a href="https://colab.research.google.com/github/Esheshwari/python-programming/blob/main/Data%20Analysis/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

# Create a Series from a list
data = [1, 3, 5, np.nan, 6]
s = pd.Series(data)
print(s)

# Print the type of the first element
print(type(data[0]))

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
dtype: float64
<class 'int'>


In [ ]:
# Create a DataFrame from a dictionary
data = {'Name': ['Ram', 'Robert','Rahim'],
'Age': [25, 30, 35],
'City': ['Ayodya', 'Chennai', 'Delhi']}
df = pd.DataFrame(data)
print(df)
print(data.values(), type(data.values()))
print(df.index, type(df.index))

     Name  Age     City
0     Ram   25   Ayodya
1  Robert   30  Chennai
2   Rahim   35    Delhi
dict_values([['Ram', 'Robert', 'Rahim'], [25, 30, 35], ['Ayodya', 'Chennai', 'Delhi']]) <class 'dict_values'>
RangeIndex(start=0, stop=3, step=1) <class 'pandas.core.indexes.range.RangeIndex'>


In [ ]:
data_x = pd.Series([0, 1, 2, 3, 4, 5])
data_y = pd.Series([0, 1, 4, 9, 16, 25])
df = pd.DataFrame({'x_value': data_x, 'square(x)': data_y})
print(df)
data_z = pd.Series([0, 1, 8, 27, 64, 125]) # Corrected Series creation
df = pd.DataFrame({"x_value": data_x, "square(x)": data_y, "cube(x)": data_z})
print(df)
print(df.values.shape, type(data.values()))

   x_value  square(x)
0        0          0
1        1          1
2        2          4
3        3          9
4        4         16
5        5         25
   x_value  square(x)  cube(x)
0        0          0        0
1        1          1        1
2        2          4        8
3        3          9       27
4        4         16       64
5        5         25      125
(6, 3) <class 'dict_values'>


In [ ]:
# Create a DataFrame from a date_range()
dates = pd.date_range("20130101", periods=6)
df_2 = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
print(dates)
print(df)
print(df_2.dtypes)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
   x_value  square(x)  cube(x)
0        0          0        0
1        1          1        1
2        2          4        8
3        3          9       27
4        4         16       64
5        5         25      125
A    float64
B    float64
C    float64
D    float64
dtype: object


In [ ]:
# Access a column
import pandas as pd
import numpy as np
# Create a DataFrame from the 'data' dictionary
df = pd.DataFrame(data) # This line was missing
print(df["Name"])
# Accessing a row by index (not label)
print(df.iloc[0])
# Access a row by index
print(df.iloc[1])
# Access a specific cell
print(df.at[0, "Age"])
# Slicing
print(df[1:3]) # Slicing rows


0       Ram
1    Robert
2     Rahim
Name: Name, dtype: object
Name       Ram
Age         25
City    Ayodya
Name: 0, dtype: object
Name     Robert
Age          30
City    Chennai
Name: 1, dtype: object
25
     Name  Age     City
1  Robert   30  Chennai
2   Rahim   35    Delhi


In [ ]:
population_dict = {'California': 38332521,
'Texas': 26448193,
'Florida': 19552860,
'Illinois': 12882135}
population = pd.Series(population_dict)
print(population_dict,type(population_dict))
print(population,type(population))
{'California': 38332521, 'Texas': 26448193, 'Florida': 19552860, 'Illinois': 12882135}

population['California']
population['California':'Illinois']

{'California': 38332521, 'Texas': 26448193, 'Florida': 19552860, 'Illinois': 12882135} <class 'dict'>
California    38332521
Texas         26448193
Florida       19552860
Illinois      12882135
dtype: int64 <class 'pandas.core.series.Series'>


California    38332521
Texas         26448193
Florida       19552860
Illinois      12882135
dtype: int64

In [ ]:
import numpy as np
A = np.random.randn(5, 3)
print(A, type(A))
dfA = pd.DataFrame(A)
print(dfA,type(dfA))

[[-0.39792725 -1.52098045  0.10121497]
 [-0.03251147 -0.66532919 -1.04968336]
 [-0.83173947  1.95566449  0.23827622]
 [ 1.18764331  0.57109747 -0.07810822]
 [ 0.60095332 -0.1007963   1.03963145]] <class 'numpy.ndarray'>
          0         1         2
0 -0.397927 -1.520980  0.101215
1 -0.032511 -0.665329 -1.049683
2 -0.831739  1.955664  0.238276
3  1.187643  0.571097 -0.078108
4  0.600953 -0.100796  1.039631 <class 'pandas.core.frame.DataFrame'>


In [ ]:
# Filter rows where Age > 25
filtered_df = df[df["Age"] > 25]
print(filtered_df)
filtered_df = df[df["Age"].isin([35])]
print(filtered_df)

     Name  Age     City
1  Robert   30  Chennai
2   Rahim   35    Delhi
    Name  Age   City
2  Rahim   35  Delhi


In [ ]:
data = {'A': [1, 2, np.nan, 4],
'B': [5, np.nan, 7, 8],
'C': [9, 10, 11, np.nan]}
df = pd.DataFrame(data)
print(df)
# Drop rows with missing values
df.dropna(inplace=True) # Modify df directly
print(df) # Print the modified DataFrame

     A    B     C
0  1.0  5.0   9.0
1  2.0  NaN  10.0
2  NaN  7.0  11.0
3  4.0  8.0   NaN
     A    B    C
0  1.0  5.0  9.0


In [ ]:
# Fill missing values with 0
df.fillna(0, inplace=True)
print(df)
# Fill missing values with the mean of the column
df["C"].fillna(df["C"].mean(), inplace=True)
print(df)
#if you are getting errors, then copy df to another dataframe

     A    B    C
0  1.0  5.0  9.0
     A    B    C
0  1.0  5.0  9.0


<ipython-input-15-623c8755d140>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["C"].fillna(df["C"].mean(), inplace=True)


In [ ]:
data = [2, 4, 6, 8]
mean = sum(data) / len(data)
print(mean)

5.0


In [ ]:
data = [2, 4, 6, 8, 10]
n = len(data)
median = sorted(data)[n // 2] if n % 2 != 0 else (sorted(data)[n // 2 - 1] + sorted(data)[n // 2]) / 2
print(median)

6


In [ ]:
import numpy as np
import pandas as pd
data = [10, 12, 13, 11, 12, 14, 10] # Example dataset without outliers
data_with_outlier = [10, 12, 13, 11, 12, 14, 10, 100] # Add an extreme outlier
# Calculate mean and median for both cases
mean_without_outlier = np.mean(data)
median_without_outlier = np.median(data)
mean_with_outlier = np.mean(data_with_outlier)
median_with_outlier = np.median(data_with_outlier)
# Print results
print(f"Mean without outlier: {mean_without_outlier:.2f}")
print(f"Median without outlier: {median_without_outlier:.2f}")
print(f"Mean with outlier: {mean_with_outlier:.2f}")
print(f"Median with outlier: {median_with_outlier:.2f}")

Mean without outlier: 11.71
Median without outlier: 12.00
Mean with outlier: 22.75
Median with outlier: 12.00


In [ ]:
from statistics import mode
data = [2, 4, 4, 6, 8]
mode_val = mode(data)
print(mode_val) # Output: 4

4


In [ ]:
#NumPy:
import numpy as np
from scipy import stats
mean = np.mean(data)
print(mean) # Output: 5.0
data = [2, 4, 6, 8, 10]
median = np.median(data)
print(median) # Output: 6.0
mode = stats.mode(data)[0]
print(mode)

In [ ]:
#Pandas:
import pandas as pd
data = [2, 4, 6, 8, 10]
df = pd.DataFrame(data, columns=['Values'])
mean = df['Values'].mean()
print(mean) # Output: 5.0
median = df['Values'].median()
print(median) # Output: 6.0
mode = df['Values'].mode()[0]
print(mode)

In [ ]:
data = [2, 4, 6, 8]
range_val = max(data) - min(data)
print(range_val)

6


In [ ]:
import numpy as np
data = [2, 4, 6, 8]
variance = np.var(data)
print(variance)

5.0


In [ ]:
import numpy as np
data = [2, 4, 6, 8]
std_dev = np.std(data)
print(std_dev)

2.23606797749979


In [ ]:
#NumPy:
import numpy as np
data = [2, 4, 6, 8]
# Peak-to-peak (range)
range_val = np.ptp(data)
print(range_val) # Output: 6
variance = np.var(data)
print(variance) # Output: 5.0
std_dev = np.std(data)
print(std_dev)

In [ ]:
#Pandas:
import pandas as pd
data = [2, 4, 6, 8]
df = pd.DataFrame(data, columns=['Values'])
range_val = df['Values'].max() - df['Values'].min()
print(range_val) # Output: 6
variance = df['Values'].var()
print(variance) # Output: 6.666666666666667
std_dev = df['Values'].std()
print(std_dev)

6
6.666666666666667
2.581988897471611


In [ ]:
from scipy.stats import skew
data = [1, 2, 3, 4, 100]
skewness = skew(data)
print(skewness) # Output: Positive Skew

1.4975367033335198


In [ ]:
from scipy.stats import kurtosis
data = [1, 2, 3, 4, 100]
kurtosis_val = kurtosis(data)
print(kurtosis_val) # Output: High Kurtosis

0.24671648930016365


In [ ]:
#NumPy:
from scipy.stats import skew
from scipy.stats import kurtosis
data = [1, 2, 3, 4, 100]
skewness = skew(data, bias=False)
print(skewness) # Output: Positive Skew
kurtosis_val = kurtosis(data, bias=False)
print(kurtosis_val) # Output: High Kurtosis

In [ ]:
#Pandas:
import pandas as pd
data = [1, 2, 3, 4, 100]
df = pd.DataFrame(data, columns=['Values'])
skewness = df['Values'].skew()
print(skewness) # Output: Positive Skew
kurtosis_val = df['Values'].kurtosis()
print(kurtosis_val) # Output: High Kurtosis

2.2323959116364573
4.986865957200655
