<a href="https://colab.research.google.com/github/Esheshwari/python-programming/blob/main/practisepython_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''Question 1
1D Arrays
Create a 1D NumPy array from a list of numbers from 1 to 10.
Create a 1D array of 20 equally spaced numbers between 0 and 1.
Generate a 1D array of 10 random integers between 1 and 100.'''
import numpy as np

# 1. Create a 1D NumPy array from a list of numbers from 1 to 10
array_1_to_10 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# 2. Create a 1D array of 20 equally spaced numbers between 0 and 1
equally_spaced_array = np.linspace(0, 1, 20)

# 3. Generate a 1D array of 10 random integers between 1 and 100
random_integers = np.random.randint(1, 101, 10)

# Print results
print("Array from 1 to 10:", array_1_to_10)
print("Equally spaced array between 0 and 1:", equally_spaced_array)
print("Random integers between 1 and 100:", random_integers)


Array from 1 to 10: [ 1  2  3  4  5  6  7  8  9 10]
Equally spaced array between 0 and 1: [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]
Random integers between 1 and 100: [ 7 46 85 49 58 42 72 93 46 16]


In [ ]:
'''Question 2
2D Arrays
Create a 2D array with 3 rows and 4 columns filled with zeros.
Generate a 2D array with the shape (5,5) containing random floating-point numbers.
Create a 2x2 identity matrix.'''
import numpy as np

# 1. Create a 2D array with 3 rows and 4 columns filled with zeros
zeros_array = np.zeros((3, 4))

# 2. Generate a 2D array with the shape (5,5) containing random floating-point numbers
random_floats_array = np.random.random((5, 5))

# 3. Create a 2x2 identity matrix
identity_matrix = np.eye(2)

# Print results
print("2D Array filled with zeros (3x4):\n", zeros_array)
print("Random floating-point numbers array (5x5):\n", random_floats_array)
print("2x2 Identity matrix:\n", identity_matrix)


2D Array filled with zeros (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Random floating-point numbers array (5x5):
 [[0.96043483 0.87558167 0.68839767 0.22625285 0.15648513]
 [0.95325762 0.18924903 0.18039338 0.73475072 0.7565032 ]
 [0.37605665 0.79101636 0.16233635 0.56971523 0.42459451]
 [0.12949876 0.91112357 0.26607258 0.90259849 0.31639987]
 [0.28314391 0.57778677 0.89618072 0.80666933 0.6669872 ]]
2x2 Identity matrix:
 [[1. 0.]
 [0. 1.]]


In [ ]:
'''Create a 3D array with the shape (3,4,2) filled with zeros.
Generate a 3D array with the shape (2,3,3) containing random integers between 1 and 10.
Convert a list of 24 sequential numbers into a 3D array with shape (2,3,4).
Calculate the mean alongthe row and column.
Calculate the mean. '''
import numpy as np

# 1. Create a 3D array with the shape (3, 4, 2) filled with zeros
zeros_3d_array = np.zeros((3, 4, 2))

# 2. Generate a 3D array with the shape (2, 3, 3) containing random integers between 1 and 10
random_ints_3d_array = np.random.randint(1, 11, (2, 3, 3))

# 3. Convert a list of 24 sequential numbers into a 3D array with shape (2, 3, 4)
sequential_numbers = np.arange(1, 25)  # List of 24 numbers from 1 to 24
sequential_3d_array = sequential_numbers.reshape(2, 3, 4)

# 4. Calculate the mean along the row (axis=1) and column (axis=2)
mean_along_rows = sequential_3d_array.mean(axis=1)  # Mean along rows
mean_along_columns = sequential_3d_array.mean(axis=2)  # Mean along columns
mean_of_3d_array = sequential_3d_array.mean()

# Print results
print("3D Array filled with zeros (3x4x2):\n", zeros_3d_array)
print("\nRandom integers array (2x3x3):\n", random_ints_3d_array)
print("\n3D Array from sequential numbers (2x3x4):\n", sequential_3d_array)
print("\nMean along rows (axis=1):\n", mean_along_rows)
print("\nMean along columns (axis=2):\n", mean_along_columns)
print("\nMean of the entire 3D array:\n", mean_of_3d_array)

3D Array filled with zeros (3x4x2):
 [[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]

Random integers array (2x3x3):
 [[[ 3  7  8]
  [ 3  8  4]
  [ 4  3  7]]

 [[ 1  1  4]
  [ 5  6  5]
  [ 1  8 10]]]

3D Array from sequential numbers (2x3x4):
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Mean along rows (axis=1):
 [[ 5.  6.  7.  8.]
 [17. 18. 19. 20.]]

Mean along columns (axis=2):
 [[ 2.5  6.5 10.5]
 [14.5 18.5 22.5]]

Mean of the entire 3D array:
 12.5


In [ ]:
'''Create a 3D array with the shape (2,3,4) filled with ones.
Generate a 4D array with the shape (2,2,2,2) containing all zeros'''
import numpy as np

# 1. Create a 3D array with the shape (2, 3, 4) filled with ones
ones_3d_array = np.ones((2, 3, 4))

# 2. Generate a 4D array with the shape (2, 2, 2, 2) containing all zeros
zeros_4d_array = np.zeros((2, 2, 2, 2))

# Print results
print("3D Array filled with ones (2x3x4):\n", ones_3d_array)
print("\n4D Array filled with zeros (2x2x2x2):\n", zeros_4d_array)


3D Array filled with ones (2x3x4):
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

4D Array filled with zeros (2x2x2x2):
 [[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]


In [ ]:
'''Given a 1D array [3, 7, 2, 9, 5, 8, 1], extract the elements at indices 1, 3, and 5.
From a 2D array with shape (4,5), extract the element at row 2, column 3.
From a 2D array, extract the entire second row.
From a 2D array, extract a subarray containing rows 1 to 3 and columns 2 to 4.'''
import numpy as np

# 1. Given a 1D array [3, 7, 2, 9, 5, 8, 1], extract the elements at indices 1, 3, and 5
array_1d = np.array([3, 7, 2, 9, 5, 8, 1])
extracted_elements = array_1d[[1, 3, 5]]

# 2. From a 2D array with shape (4,5), extract the element at row 2, column 3
array_2d = np.array([[10, 20, 30, 40, 50],
                     [60, 70, 80, 90, 100],
                     [110, 120, 130, 140, 150],
                     [160, 170, 180, 190, 200]])
element_at_2_3 = array_2d[2, 3]

# 3. From a 2D array, extract the entire second row
second_row = array_2d[1, :]

# 4. From a 2D array, extract a subarray containing rows 1 to 3 and columns 2 to 4
subarray = array_2d[1:4, 2:5]

# Print results
print("Extracted elements from 1D array:", extracted_elements)
print("Element at row 2, column 3 in 2D array:", element_at_2_3)
print("Second row from 2D array:", second_row)
print("Subarray from 2D array (rows 1 to 3, columns 2 to 4):\n", subarray)


Extracted elements from 1D array: [7 9 8]
Element at row 2, column 3 in 2D array: 140
Second row from 2D array: [ 60  70  80  90 100]
Subarray from 2D array (rows 1 to 3, columns 2 to 4):
 [[ 80  90 100]
 [130 140 150]
 [180 190 200]]


In [ ]:
'''From a 3D array with shape (3,4,5), extract the element at position (depth 1,row 2,col 3).
From a 3D array, extract the entire first "layer" (all rows and columns of the first depth index).
From a 3D array of shape (4,5,6), extract a subarray containing depths 1 to 3, rows 2 to 4, and columns 3 to 5.'''
import numpy as np

# Create a 3D array with shape (3, 4, 5)
array_3d = np.random.randint(1, 100, (3, 4, 5))

# 1. Extract the element at position (depth 1, row 2, col 3)
element_at_position = array_3d[1, 2, 3]

# 2. Extract the entire first "layer" (all rows and columns of the first depth index)
first_layer = array_3d[0, :, :]

# 3. Extract a subarray from a 3D array of shape (4, 5, 6) containing depths 1 to 3, rows 2 to 4, and columns 3 to 5
array_3d_large = np.random.randint(1, 100, (4, 5, 6))
subarray = array_3d_large[1:4, 2:5, 3:6]

# Print results
print("Element at position (depth 1, row 2, col 3):", element_at_position)
print("\nEntire first 'layer' (depth 0):\n", first_layer)
print("\nSubarray from depths 1 to 3, rows 2 to 4, and columns 3 to 5:\n", subarray)

Element at position (depth 1, row 2, col 3): 70

Entire first 'layer' (depth 0):
 [[82 41 19 23 82]
 [91 48 14 77 19]
 [61 79 50 22 43]
 [13 37 95 69 16]]

Subarray from depths 1 to 3, rows 2 to 4, and columns 3 to 5:
 [[[98 41 90]
  [53 94 26]
  [ 3  1  2]]

 [[ 5 30 17]
  [93 72 83]
  [62 66 17]]

 [[40 30 82]
  [63 73 21]
  [97  4 36]]]


In [ ]:
'''Reshape a 1D array of 12 elements into a 3x4 2D array.
Reshape a 2D array of shape (3,4) into a 1D array.
Transpose a 2D array of shape (2,5).'''
import numpy as np

# 1. Reshape a 1D array of 12 elements into a 3x4 2D array
array_1d = np.arange(1, 13)  # 1D array with 12 elements
reshaped_2d = array_1d.reshape(3, 4)

# 2. Reshape a 2D array of shape (3,4) into a 1D array
array_2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])
reshaped_1d = array_2d.reshape(-1)

# 3. Transpose a 2D array of shape (2, 5)
array_2d_transpose = np.array([[1, 2, 3, 4, 5],
                                [6, 7, 8, 9, 10]])
transposed_array = array_2d_transpose.T  # or array_2d_transpose.transpose()

# Print results
print("Reshaped 1D array into 3x4 2D array:\n", reshaped_2d)
print("\nReshaped 2D array into 1D array:\n", reshaped_1d)
print("\nTransposed 2D array (2,5) into (5,2):\n", transposed_array)


In [ ]:
'''Reshape a 3D array of shape (2,3,4) into a 2D array of shape (6,4).
Transpose a 3D array, swapping the first and third dimensions.
Stack two 2D arrays of shape (3,4) to create a 3D array of shape (2,3,4).'''
import numpy as np

# 1. Reshape a 3D array of shape (2, 3, 4) into a 2D array of shape (6, 4)
arr_3d = np.arange(1, 25).reshape(2, 3, 4)
reshaped_2d = arr_3d.reshape(6, 4)

# 2. Transpose a 3D array, swapping the first and third dimensions
transposed_3d = arr_3d.transpose(2, 1, 0)

# 3. Stack two 2D arrays of shape (3, 4) to create a 3D array of shape (2, 3, 4)
arr_2d_1 = np.random.randint(1, 10, (3, 4))
arr_2d_2 = np.random.randint(1, 10, (3, 4))
stacked_3d = np.stack((arr_2d_1, arr_2d_2), axis=0)

# Print results
print("Reshaped 3D to 2D (6x4):\n", reshaped_2d)
print("\nTransposed 3D array:\n", transposed_3d)
print("\nStacked 2D arrays into 3D (2,3,4):\n", stacked_3d)


In [ ]:
'''Add two 1D arrays of the same length element-wise.
Multiply a 2D array by a scalar value.
Calculate the square root of each element in an array.'''
import numpy as np

# 1. Add two 1D arrays of the same length element-wise
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
added_arrays = arr1 + arr2

# 2. Multiply a 2D array by a scalar value
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
scalar_value = 3
multiplied_array = arr_2d * scalar_value

# 3. Calculate the square root of each element in an array
arr = np.array([1, 4, 9, 16, 25])
sqrt_array = np.sqrt(arr)

# Print results
print("Added 1D arrays element-wise:", added_arrays)
print("\n2D array multiplied by scalar:", multiplied_array)
print("\nSquare root of each element in the array:", sqrt_array)


Added 1D arrays element-wise: [6 6 6 6 6]

2D array multiplied by scalar: [[ 3  6  9]
 [12 15 18]]

Square root of each element in the array: [1. 2. 3. 4. 5.]


In [ ]:
'''Perform element-wise addition between two 3D arrays of the same shape.
Calculate the mean along the second axis of a 3D array.
Apply a function (like np.sin) to each element of a 3D array.'''
import numpy as np

# 1. Perform element-wise addition between two 3D arrays of the same shape
arr1_3d = np.random.randint(1, 10, (2, 3, 4))  # A random 3D array of shape (2, 3, 4)
arr2_3d = np.random.randint(1, 10, (2, 3, 4))  # Another random 3D array of the same shape
added_3d_arrays = arr1_3d + arr2_3d

# 2. Calculate the mean along the second axis (axis=1) of a 3D array
mean_second_axis = arr1_3d.mean(axis=1)

# 3. Apply a function (like np.sin) to each element of a 3D array
sin_of_3d = np.sin(arr1_3d)

# Print results
print("Element-wise addition of two 3D arrays:\n", added_3d_arrays)
print("\nMean along the second axis (axis=1):\n", mean_second_axis)
print("\nSin of each element in the 3D array:\n", sin_of_3d)


Element-wise addition of two 3D arrays:
 [[[13 11  6 11]
  [10 12 12 11]
  [14 17  8  4]]

 [[ 9  5 14  7]
  [10 10  9 14]
  [10  8  6  4]]]

Mean along the second axis (axis=1):
 [[4.         7.33333333 5.33333333 3.66666667]
 [7.         3.66666667 6.33333333 4.        ]]

Sin of each element in the 3D array:
 [[[-0.95892427  0.41211849  0.14112001 -0.7568025 ]
  [ 0.90929743 -0.95892427  0.6569866  -0.2794155 ]
  [-0.95892427  0.98935825 -0.2794155   0.84147098]]

 [[-0.95892427  0.14112001  0.41211849  0.14112001]
  [ 0.6569866   0.14112001 -0.2794155   0.98935825]
  [ 0.41211849 -0.95892427 -0.7568025   0.84147098]]]


In [ ]:
#V.IMP FOR EXAM
import numpy as np
np.random.seed(100)
test=np.random.randint(1,101,(3,4,5))#understand how is it cal mean
print(test)
print(np.mean(test, axis=0))

[[[ 9 25 68 88 80]
  [49 11 95 53 99]
  [54 67 99 15 35]
  [25 16 61 59 17]]

 [[10 94 87  3 28]
  [ 5 32  2 14 84]
  [ 5 92 60 68  8]
  [50 48 66 62 15]]

 [[56 72 81  3 95]
  [20 99 64 54 28]
  [57 31 49 48 40]
  [39 45 19 65 57]]]
[[25.         63.66666667 78.66666667 31.33333333 67.66666667]
 [24.66666667 47.33333333 53.66666667 40.33333333 70.33333333]
 [38.66666667 63.33333333 69.33333333 43.66666667 27.66666667]
 [38.         36.33333333 48.66666667 62.         29.66666667]]


In [ ]:
#V.IMP FOR EXAM
import numpy as np
np.random.seed(100)
test=np.random.randint(1,101,(3,4,5))#understand how is it cal mean
print(test)
print(np.mean(test, axis=2))

[[[ 9 25 68 88 80]
  [49 11 95 53 99]
  [54 67 99 15 35]
  [25 16 61 59 17]]

 [[10 94 87  3 28]
  [ 5 32  2 14 84]
  [ 5 92 60 68  8]
  [50 48 66 62 15]]

 [[56 72 81  3 95]
  [20 99 64 54 28]
  [57 31 49 48 40]
  [39 45 19 65 57]]]
[[54.  61.4 54.  35.6]
 [44.4 27.4 46.6 48.2]
 [61.4 53.  45.  45. ]]


In [ ]:
mean = test[1].mean()indexing
print(mean)

41.65


In [ ]:
'''Add a 1D array of shape (3,) to each row of a 2D array with shape (4,3).
Multiply a 2D array of shape (3,4) with a 1D array of shape (4,).'''
import numpy as np

# 1. Add a 1D array of shape (3,) to each row of a 2D array with shape (4, 3)
arr_2d = np.random.randint(1, 10, (4, 3))  # A 2D array of shape (4, 3)
arr_1d = np.array([1, 2, 3])  # A 1D array of shape (3,)
added_result = arr_2d + arr_1d  # Broadcasting the addition

# 2. Multiply a 2D array of shape (3, 4) with a 1D array of shape (4,)
arr_2d_2 = np.random.randint(1, 10, (3, 4))  # A 2D array of shape (3, 4)
arr_1d_2 = np.array([1, 2, 3, 4])  # A 1D array of shape (4,)
multiplied_result = arr_2d_2 * arr_1d_2  # Element-wise multiplication (broadcasting)

# Print results
print("Result of adding 1D array to each row of a 2D array:\n", added_result)
print("\nResult of multiplying 2D array with 1D array:\n", multiplied_result)


Result of adding 1D array to each row of a 2D array:
 [[ 4  8  5]
 [10  4  9]
 [ 6  5 12]
 [ 5  8  4]]

Result of multiplying 2D array with 1D array:
 [[ 4 14 12 20]
 [ 8 14 12  4]
 [ 5 10 18 32]]


In [ ]:
'''Add a 1D array of shape (4,) to each "row" across all "layers" of a 3D array with shape (3,5,4).
Multiply a 2D array of shape (3,4) with each "layer" of a 3D array with shape (2,3,4).
Scale each "layer" of a 3D array with shape (4,3,5) by a different scalar value from a 1D array of shape (4,).'''
import numpy as np

# Initialize arrays
arr_3d_1 = np.random.rand(3, 5, 4)  # Shape (3,5,4)
arr_1d = np.random.rand(4)          # Shape (4,)

arr_3d_2 = np.random.rand(2, 3, 4)  # Shape (2,3,4)
arr_2d = np.random.rand(3, 4)       # Shape (3,4)

arr_3d_3 = np.random.rand(4, 3, 5)  # Shape (4,3,5)
scalars = np.random.rand(4)         # Shape (4,)

# Perform operations
result_1 = arr_3d_1 + arr_1d  # Adding 1D array to each row across layers
result_2 = arr_3d_2 * arr_2d  # Multiplying 2D array with each layer
result_3 = arr_3d_3 * scalars[:, np.newaxis, np.newaxis]  # Scaling each layer by different scalars

# Display results
print("Result 1:\n", result_1)
print("Result 2:\n", result_2)
print("Result 3:\n", result_3)


Result 1:
 [[[1.36007247 0.94883407 1.03126414 1.78989272]
  [0.93745111 1.42377951 1.44080804 1.03021148]
  [1.08243645 0.61452077 1.2688849  1.44161255]
  [1.41217712 0.91173872 1.16770404 1.42437385]
  [1.13729885 0.78452534 1.17944616 1.05513972]]

 [[1.14684965 0.91669015 1.75719054 1.57629294]
  [1.4656808  0.80028649 1.20185376 1.50196769]
  [1.40662902 0.53838481 0.99114292 1.30297154]
  [0.85532726 1.38648914 1.69572997 1.36709317]
  [0.91386329 0.55976596 1.83718457 1.55397598]]

 [[1.55556659 0.81201987 1.10894825 1.1463705 ]
  [1.55248656 0.89783123 1.52139127 1.65266109]
  [0.94857153 0.50442068 1.59087483 1.80832996]
  [1.64939576 0.91534629 1.49030629 1.5799275 ]
  [1.59800053 0.58709416 1.26399555 1.26402322]]]
Result 2:
 [[[0.06786099 0.06377474 0.40326026 0.03525881]
  [0.01398979 0.66792714 0.02040341 0.09444526]
  [0.0438393  0.02625208 0.06599682 0.15128444]]

 [[0.53556836 0.1041663  0.13142709 0.26064405]
  [0.0154072  0.05769429 0.01599997 0.25555188]
  [0.07019

In [ ]:
'''Create a pandas Series with the values [5, 10, 15, 20, 25].
Create a Series with values [100, 200, 300, 400, 500] and index labels ['a', 'b', 'c', 'd', 'e'].
Create a Series from this dictionary: {'apple': 3, 'banana': 5, 'orange': 2}.
For the Series s = pd.Series([10, 20, 30, 40, 50]):
Find its length
Find its mean value
Find its maximum value'''
import pandas as pd

# 1. Create a Series with values [5, 10, 15, 20, 25]
series1 = pd.Series([5, 10, 15, 20, 25])
print("Series 1:\n", series1)

# 2. Create a Series with values [100, 200, 300, 400, 500] and index labels ['a', 'b', 'c', 'd', 'e']
series2 = pd.Series([100, 200, 300, 400, 500], index=['a', 'b', 'c', 'd', 'e'])
print("\nSeries 2:\n", series2)

# 3. Create a Series from a dictionary
fruit_dict = {'apple': 3, 'banana': 5, 'orange': 2}
series3 = pd.Series(fruit_dict)
print("\nSeries 3:\n", series3)

# 4. Perform operations on the given Series
s = pd.Series([10, 20, 30, 40, 50])

# Find its length
length = len(s)

# Find its mean value
mean_value = s.mean()

# Find its maximum value
max_value = s.max()

print("\nSeries s:")
print("Length:", length)
print("Mean value:", mean_value)
print("Maximum value:", max_value)

In [ ]:
'''Create a DataFrame from this dictionary:
data = {
    'Name': ['John', 'Emma', 'Alex'],
    'Age': [25, 30, 22],
    'City': ['New York', 'London', 'Paris']
}

Create a simple DataFrame with 3 rows and 2 columns named 'A' and 'B' with any numbers you choose.
Convert this list of lists into a DataFrame with column names 'Product', 'Price', 'Quantity':
data = [
    ['Apple', 1.2, 10],
    ['Banana', 0.5, 15],
    ['Orange', 0.8, 8]
]'''
import pandas as pd

# 1. Create a DataFrame from a dictionary
data = {
    'Name': ['John', 'Emma', 'Alex'],
    'Age': [25, 30, 22],
    'City': ['New York', 'London', 'Paris']
}
df1 = pd.DataFrame(data)
print("DataFrame 1:\n", df1)

# 2. Create a simple DataFrame with 3 rows and 2 columns named 'A' and 'B'
df2 = pd.DataFrame({
    'A': [10, 20, 30],
    'B': [40, 50, 60]
})
print("\nDataFrame 2:\n", df2)

# 3. Convert a list of lists into a DataFrame with column names 'Product', 'Price', 'Quantity'
data_list = [
    ['Apple', 1.2, 10],
    ['Banana', 0.5, 15],
    ['Orange', 0.8, 8]
]
df3 = pd.DataFrame(data_list, columns=['Product', 'Price', 'Quantity'])
print("\nDataFrame 3:\n", df3)

In [ ]:
'''For the DataFrame created in question 5:
Display the column names
Display the first 2 rows
Display information about the DataFrame (hint: use .info())
Using this DataFrame:
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

Select column 'A'
Select columns 'A' and 'C'
Select the value at row 1, column 'B' '''
import pandas as pd

# DataFrame from question 5
df1 = pd.DataFrame({
    'Name': ['John', 'Emma', 'Alex'],
    'Age': [25, 30, 22],
    'City': ['New York', 'London', 'Paris']
})

# 1. Display the column names
print("Column names:", df1.columns.tolist())

# 2. Display the first 2 rows
print("\nFirst 2 rows:\n", df1.head(2))

# 3. Display information about the DataFrame
print("\nDataFrame Info:")
df1.info()

# New DataFrame for selection operations
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

# 4. Select column 'A'
column_a = df['A']
print("\nColumn A:\n", column_a)

# 5. Select columns 'A' and 'C'
columns_ac = df[['A', 'C']]
print("\nColumns A and C:\n", columns_ac)

# 6. Select the value at row 1, column 'B'
value_b1 = df.at[1, 'B']
print("\nValue at row 1, column 'B':", value_b1)


Column names: ['Name', 'Age', 'City']

First 2 rows:
    Name  Age      City
0  John   25  New York
1  Emma   30    London

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

Column A:
 0    1
1    2
2    3
Name: A, dtype: int64

Columns A and C:
    A  C
0  1  7
1  2  8
2  3  9

Value at row 1, column 'B': 5


In [ ]:
'''Using this DataFrame:
df = pd.DataFrame({
    'Name': ['John', 'Emma', 'Alex', 'Sarah', 'Mike'],
    'Age': [25, 30, 22, 28, 32],
    'City': ['New York', 'London', 'Paris', 'Berlin', 'Tokyo'],
    'Salary': [50000, 60000, 45000, 55000, 65000]
})
Select rows where Age > 25
Select rows where City is 'London' or 'Paris'
Select rows where Salary is between 45000 and 60000'''
import pandas as pd

# Creating the DataFrame
df = pd.DataFrame({
    'Name': ['John', 'Emma', 'Alex', 'Sarah', 'Mike'],
    'Age': [25, 30, 22, 28, 32],
    'City': ['New York', 'London', 'Paris', 'Berlin', 'Tokyo'],
    'Salary': [50000, 60000, 45000, 55000, 65000]
})

# 1. Select rows where Age > 25
age_filter = df[df['Age'] > 25]
print("Rows where Age > 25:\n", age_filter)

# 2. Select rows where City is 'London' or 'Paris'
city_filter = df[df['City'].isin(['London', 'Paris'])]
print("\nRows where City is 'London' or 'Paris':\n", city_filter)

# 3. Select rows where Salary is between 45000 and 60000
salary_filter = df[(df['Salary'] >= 45000) & (df['Salary'] <= 60000)]
print("\nRows where Salary is between 45000 and 60000:\n", salary_filter)

In [ ]:
'''Create a DataFrame with some missing values:
df = pd.DataFrame({
    'A': [1, 2, None, 4],
    'B': [5, None, 7, 8],
    'C': [9, 10, 11, None]
})
Count the number of missing values in each column
Drop rows with any missing values
Fill all missing values with 0

Using the DataFrame from previous question:
Fill missing values in column 'A' with the mean of column 'A'
Fill missing values in column 'B' with the value 100
Replace all missing values with the previous valid value (hint: use .ffill())'''
import pandas as pd

# Creating DataFrame with missing values
df = pd.DataFrame({
    'A': [1, 2, None, 4],
    'B': [5, None, 7, 8],
    'C': [9, 10, 11, None]
})

# 1. Count the number of missing values in each column
missing_counts = df.isnull().sum()
print("Missing values in each column:\n", missing_counts)

# 2. Drop rows with any missing values
df_dropped = df.dropna()
print("\nDataFrame after dropping rows with missing values:\n", df_dropped)

# 3. Fill all missing values with 0
df_filled_0 = df.fillna(0)
print("\nDataFrame after filling missing values with 0:\n", df_filled_0)

# Handling missing values in specific ways
df = pd.DataFrame({
    'A': [1, 2, None, 4],
    'B': [5, None, 7, 8],
    'C': [9, 10, 11, None]
})

# 4. Fill missing values in column 'A' with the mean of column 'A'
df['A'].fillna(df['A'].mean(), inplace=True)

# 5. Fill missing values in column 'B' with the value 100
df['B'].fillna(100, inplace=True)

# 6. Replace all missing values with the previous valid value
df.ffill(inplace=True)

print("\nFinal DataFrame after handling missing values:\n", df)

In [ ]:
'''Create a DataFrame with student test scores:
df = pd.DataFrame({
    'Student': ['Alex', 'Bob', 'Charlie', 'David'],
    'Math': [85, 90, 70, 80],
    'Science': [90, 85, 75, 85],
    'English': [80, 95, 80, 75]
})

Add a new column 'Average' that contains the average score for each student
Sort the DataFrame by the Math scores in descending order
Find the student with the highest Science score

For the DataFrame in previous question:
Find all students who scored above 85 in any subject
Calculate the average score for each subject
Add a new row for a student named 'Eve' with scores Math: 95, Science: 92, English: 88

Using the following DataFrame:
df = pd.DataFrame({
    'Product': ['A', 'B', 'A', 'C', 'B', 'A'],
    'Quantity': [10, 5, 15, 8, 12, 7],
    'Price': [100, 200, 100, 150, 200, 100]
})

Calculate the total quantity for each product
Calculate the total revenue (Quantity * Price) for each product'''
import pandas as pd

# Creating the student test scores DataFrame
df = pd.DataFrame({
    'Student': ['Alex', 'Bob', 'Charlie', 'David'],
    'Math': [85, 90, 70, 80],
    'Science': [90, 85, 75, 85],
    'English': [80, 95, 80, 75]
})

# 1. Add a new column 'Average' that contains the average score for each student
df['Average'] = df[['Math', 'Science', 'English']].mean(axis=1)
print("DataFrame with Average Score:\n", df)

# 2. Sort the DataFrame by the Math scores in descending order
df_sorted_math = df.sort_values(by='Math', ascending=False)
print("\nDataFrame sorted by Math scores:\n", df_sorted_math)

# 3. Find the student with the highest Science score
top_science_student = df[df['Science'] == df['Science'].max()]['Student'].values[0]
print("\nStudent with the highest Science score:", top_science_student)

# 4. Find all students who scored above 85 in any subject
students_above_85 = df[(df['Math'] > 85) | (df['Science'] > 85) | (df['English'] > 85)]
print("\nStudents who scored above 85 in any subject:\n", students_above_85)

# 5. Calculate the average score for each subject
average_per_subject = df[['Math', 'Science', 'English']].mean()
print("\nAverage score for each subject:\n", average_per_subject)

# 6. Add a new row for a student named 'Eve' with scores Math: 95, Science: 92, English: 88
df.loc[len(df)] = ['Eve', 95, 92, 88, (95+92+88)/3]
print("\nDataFrame after adding Eve:\n", df)

DataFrame with Average Score:
    Student  Math  Science  English  Average
0     Alex    85       90       80     85.0
1      Bob    90       85       95     90.0
2  Charlie    70       75       80     75.0
3    David    80       85       75     80.0

DataFrame sorted by Math scores:
    Student  Math  Science  English  Average
1      Bob    90       85       95     90.0
0     Alex    85       90       80     85.0
3    David    80       85       75     80.0
2  Charlie    70       75       80     75.0

Student with the highest Science score: Alex

Students who scored above 85 in any subject:
   Student  Math  Science  English  Average
0    Alex    85       90       80     85.0
1     Bob    90       85       95     90.0

Average score for each subject:
 Math       81.25
Science    83.75
English    82.50
dtype: float64

DataFrame after adding Eve:
    Student  Math  Science  English    Average
0     Alex    85       90       80  85.000000
1      Bob    90       85       95  90.000000
2  C

'''Mean Calculation: Given the data set [3, 7, 9, 12, 15], calculate the mean. What does this mean in the context of the data?
Kurtosis Interpretation: What does kurtosis indicate about a data set? Describe how you would identify whether a data set has high or low kurtosis.
Median vs. Mean: Explain the difference between the mean and median. When is it more appropriate to use the median instead of the mean?
Mode Identification: Given the data set [2, 4, 4, 6, 8, 8, 8, 10], identify the mode. How would you interpret the mode in this context?
Range Calculation: Calculate the range for the following data set: [3, 5, 8, 12, 14]. What does the range tell you about the spread of the data?
Variance Calculation: Given the data set [1, 3, 5, 7], calculate the sample variance. What does variance tell you about the distribution of the data?
Standard Deviation: How does standard deviation help in understanding data spread? Calculate the standard deviation for the data set [5, 7, 10, 12, 14].
Skewness Analysis: Given the data set [2, 3, 4, 5, 100], describe the skewness of the data and explain what this means.'''
=>

In [ ]:
# Mean Calculation
import numpy as np

data = [3, 7, 9, 12, 15]
mean_value = np.mean(data)
print("Mean:", mean_value)

# Kurtosis Interpretation
from scipy.stats import kurtosis

data = [3, 7, 9, 12, 15]
kurtosis_value = kurtosis(data, fisher=False)
print("Kurtosis:", kurtosis_value)

# Median vs. Mean
data = [10, 20, 30, 40, 1000]
mean_value = np.mean(data)
median_value = np.median(data)
print("Mean:", mean_value, "Median:", median_value)

# Mode Identification
from scipy.stats import mode

data = [2, 4, 4, 6, 8, 8, 8, 10]
mode_value = mode(data).mode[0]
print("Mode:", mode_value)

# Range Calculation
data = [3, 5, 8, 12, 14]
range_value = max(data) - min(data)
print("Range:", range_value)

# Variance Calculation
data = [1, 3, 5, 7]
variance_value = np.var(data, ddof=1)
print("Sample Variance:", variance_value)

# Standard Deviation Calculation
data = [5, 7, 10, 12, 14]
std_dev = np.std(data, ddof=1)
print("Standard Deviation:", std_dev)

# Skewness Analysis
from scipy.stats import skew

data = [2, 3, 4, 5, 100]
skewness_value = skew(data)
print("Skewness:", skewness_value)

In [ ]:
''' Create a dictionary with the following key-value pairs:
"name": "John"
"age": 30
"city": "New York"
Print the dictionary.'''
# Creating the dictionary
person = {
    "name": "John",
    "age": 30,
    "city": "New York"
}

# Printing the dictionary
print(person)

{'name': 'John', 'age': 30, 'city': 'New York'}


In [ ]:
'''Question 21:
 Write a Python program to read the contents of a file named data.txt. Assume the file contains multiple lines of text. Print each line in the file.'''
# Create a sample file
with open("data.txt", "w") as file:
    file.write("Hello, this is line 1.\n")
    file.write("This is line 2.\n")
    file.write("And this is line 3.\n")

print("File 'data.txt' created successfully.")

File 'data.txt' created successfully.


In [ ]:
''' Write a Python program to create a file called output.txt and write the text "Hello, World!" into it. Ensure the file is saved in the current directory.'''
# Open the file in write mode
with open("output.txt", "w") as file:
    file.write("Hello, World!")

print("File 'output.txt' created successfully with text.")
import os
print("File exists:", os.path.exists("output.txt"))#true=is created

File 'output.txt' created successfully with text.
File exists: True


In [ ]:
''' Create a dictionary with the key "product" and the value "laptop". Then, update the dictionary by adding
a new key-value pair "price": 1000. Print the updated dictionary.'''
# Create the dictionary
item = {"product": "laptop"}

# Update the dictionary with a new key-value pair
item["price"] = 1000

# Print the updated dictionary
print(item)

{'product': 'laptop', 'price': 1000}


In [ ]:
''' Use the with statement to open a file named example.txt for reading, and then print its contents.
What is the advantage of using with for file handling?'''
#create file example.txt
import os

filename = "example.txt"

# Step 1: Check if the file exists, if not, create it
if not os.path.exists(filename):
    with open(filename, "w") as file:
        file.write("This is an example file.\nIt contains multiple lines of text.\nHello, World!")
    print(f"File '{filename}' was missing and has now been created.")

# Step 2: Read and print the file contents
with open(filename, "r") as file:
    contents = file.read()
    print("\n--- File Contents ---")
    print(contents)

# Advantages of using 'with' for file handling
print("\n--- Advantages of Using 'with' for File Handling ---")
print("1. Ensures the file is automatically closed after operations.")
print("2. Prevents resource leaks, even if an error occurs.")
print("3. Makes the code cleaner and more readable.")


--- File Contents ---
This is an example file.
It contains multiple lines of text.
Hello, World!

--- Advantages of Using 'with' for File Handling ---
1. Ensures the file is automatically closed after operations.
2. Prevents resource leaks, even if an error occurs.
3. Makes the code cleaner and more readable.
